### ISSUE TITLE
[Editor][Photo] Photos inserted through the editor aren't displayed correctly - a tool is required to ensure functionality

### ISSUE THREAD

**Issue by SophiaMRI** [ita-social-projects/StreetCode#1132]
**Environment:** All
**Reproducible:** Always
**Build found:** [61192c2](https://github.com/ita-social-projects/StreetCode/commit/61192c212ff01065c711324c06717333e907d8bb)

**Steps to reproduce**
1. Go to the page where the editor window is present (e.g. the 'News' page).
2. Click on the 'Створити новину' button.
3. Add data to all mandatory fields.
4. Drag a photo into the text field.
5. Go to the user side and pay attention to the place where the photo should be.

**Actual result**
1. Empty space where the photo should be.
2. There isn't a tool to provide functionality for adding photos.

**Expected result**
1. The photo is displayed correctly.
2. There is a tool to provide functionality for adding photos.
https://streetcode.com.ua/news/teper-v-nas-ye-ngo

### ! Note from dev:
Think about how to store the pasted image, because by default it will be stored as base64 directly in the entity text field in DB. Consequently, we get a text of 65,000+ characters.

**Comment by darkravchuk** [comment]
it is not specified in the requirements
