### ISSUE TITLE
[StreetCode Page] [UI ][Main StreetCode block] The "Оживити картинку" button is displayed under the "Teaser" at the right bottom of the screen on the tablet version.

### ISSUE THREAD

**Issue by AlbinaVorobiova** [ita-social-projects/StreetCode#1203]
**Environment:** iPadOS 16.5.1, Safari 
**Reproducible:** always
**Build found:** ?

**Preconditions:**
1. Go to the site using iPad: https://streetcode.com.ua/

**Steps to reproduce:**
1. Enter "Грушевський" in the "Search" field.
2. Open the "Грушевський" streetcode.
3. Scroll down under the text of the "Teaser" (about the person). 

**Actual result:**
The "Оживити картинку" button is displayed and clickable under the "Teaser" at the right bottom of the screen.

![скрін бага (2)](https://github.com/ita-social-projects/StreetCode/assets/160258291/a21d619c-0f1c-4b23-ab23-a91fad31ec0c)

**Expected result:**
The "Оживити картинку" button is not displayed under the "Teaser" on the tablet version (according to the Mockup and User story).
![мокап планшет_немає кнопки Оживити картинку](https://github.com/ita-social-projects/StreetCode/assets/160258291/a51c3911-f46f-4396-972b-e97b2660e814)

Epic: [#19](https://github.com/ita-social-projects/StreetCode/issues/19)
User story: [#20](https://github.com/ita-social-projects/StreetCode/issues/20)
Test case: https://github.com/ita-social-projects/StreetCode/issues/64

**Comment by SophiaMRI** [comment]
The 'Оживити картинку' button is no longer supported.

**Comment by AlbinaVorobiova** [comment]
The 'Оживити картинку' button is removed (according to the Customer`s requirement).
