### ISSUE TITLE
Database timeout issue Root cause analysis

### ISSUE THREAD

**Issue by LanchevychMaxym** [ita-social-projects/StreetCode#1206]
This issue happens after redeployment of Frontend client to Stage. Firstly, Backend service is unhealthy because it can't access database, so all requests fail with CORS error. After some time database is coming up and backend is available, but streetcode apis fail.

**Environment:** Stage
**Reproducible:** unknown
**Build found:** 
- Stage_deploy - 273
- Stage_deploy - 272

**Actual result**
Streetcode specific requests fail

**Expected result**
Streetcode functionality works as expected

**Preconditions**
- database is available
- blob storage is available
- 

**Attachments**
![image](https://github.com/ita-social-projects/StreetCode/assets/47561209/c51ad4ca-9c53-4063-9599-ab5642221d5f)
![image](https://github.com/ita-social-projects/StreetCode/assets/47561209/06f20bdb-b40a-4644-969b-7b8009284458)
![image](https://github.com/ita-social-projects/StreetCode/assets/113620149/f7c8a78f-7441-42f8-b746-07bca2aee579)
![image](https://github.com/ita-social-projects/StreetCode/assets/113620149/44c8a734-7e49-4d86-8c3d-d717cd4b49f4)
![image](https://github.com/ita-social-projects/StreetCode/assets/113620149/410a2328-f7c5-4424-b9f5-fb14544bd0cd)

sudo grep "Error" /var/opt/mssql/log/errorlog
2024-02-29 19:18:25.22 Server      Error searching first file in /var/opt/mssql/security/ca-certificates: 3(The system cannot find the path specified.)
2024-02-29 19:18:34.79 spid51      Error: 17066, Severity: 16, State: 1.
2024-02-29 19:18:36.64 spid51      Error: 3624, Severity: 20, State: 1.
admin_1@Stage:~$

sudo grep "Error" /var/opt/mssql/log/errorlog
2024-02-29 19:18:25.22 Server      Error searching first file in /var/opt/mssql/security/ca-certificates: 3(The system cannot find the path specified.)
2024-02-29 19:18:34.79 spid51      Error: 17066, Severity: 16, State: 1.
2024-02-29 19:18:36.64 spid51      Error: 3624, Severity: 20, State: 1.
2024-02-29 19:22:31.62 Logon       Error: 18456, Severity: 14, State: 5.

![image](https://github.com/ita-social-projects/StreetCode/assets/47561209/00ab792d-1b01-4a94-bbb7-dffd0182b5f5)

![image](https://github.com/ita-social-projects/StreetCode/assets/47561209/bc848e5b-3d29-4d96-a44a-f60ef2a44bd0)
![image](https://github.com/ita-social-projects/StreetCode/assets/47561209/0125969a-2ded-401b-a812-88b241c0328b)

Logs from docker container of database:
<html>
<body>

[19:48:11 INF] Start installing Hangfire SQL objects... |  
-- | --
  |   | Error Number:-2,State:0,Class:11 |  
  |   | ClientConnectionId:dffa3900-ab7f-4de8-bd25-0c9f06ba4e0c |  
  |   | at Streetcode.WebApi.Extensions.WebApplicationExtensions.ApplyMigrations(WebApplication app) in /Streetcode.WebApi/Extensions/WebApplicationExtensions.cs:line 14 |  
  |   | at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.MigrateAsync(String targetMigration, CancellationToken cancellationToken) |  
  |   | at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQueryAsync(IEnumerable`1 migrationCommands, IRelationalConnection connection, CancellationToken cancellationToken) |  
  |   | at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQueryAsync(IEnumerable`1 migrationCommands, IRelationalConnection connection, CancellationToken cancellationToken) |  
  |   | at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQueryAsync(IEnumerable`1 migrationCommands, IRelationalConnection connection, CancellationToken cancellationToken) |  
  |   | at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQueryAsync(IEnumerable`1 migrationCommands, IRelationalConnection connection, CancellationToken cancellationToken) |  
  |   | at Microsoft.EntityFrameworkCore.Storage.RelationalTransaction.CommitAsync(CancellationToken cancellationToken) |  
  |   | at Microsoft.EntityFrameworkCore.Storage.RelationalTransaction.CommitAsync(CancellationToken cancellationToken) |  
  |   | --- End of stack trace from previous location --- |  
  |   | at System.Data.Common.DbTransaction.CommitAsync(CancellationToken cancellationToken) |  
  |   | at Microsoft.Data.SqlClient.SqlTransaction.Commit() |  
  |   | at Microsoft.Data.SqlClient.SqlInternalTransaction.Commit() |  
  |   | at Microsoft.Data.SqlClient.SqlInternalConnectionTds.ExecuteTransaction(TransactionRequest transactionRequest, String name, IsolationLevel iso, SqlInternalTransaction internalTransaction, Boolean isDelegateControlRequest) |  
  |   | at Microsoft.Data.SqlClient.SqlInternalConnectionTds.ExecuteTransaction2005(TransactionRequest transactionRequest, String transactionName, IsolationLevel iso, SqlInternalTransaction internalTransaction, Boolean isDelegateControlRequest) |  
  |   | at Microsoft.Data.SqlClient.TdsParser.TdsExecuteTransactionManagerRequest(Byte[] buffer, TransactionManagerRequestType request, String transactionName, TransactionManagerIsolationLevel isoLevel, Int32 timeout, SqlInternalTransaction transaction, TdsParserStateObject stateObj, Boolean isDelegateControlRequest) |  
  |   | at Microsoft.Data.SqlClient.TdsParser.Run(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj) |  
  |   | at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady) |  
  |   | at Microsoft.Data.SqlClient.TdsParserStateObject.TryReadByte(Byte& value) |  
  |   | at Microsoft.Data.SqlClient.TdsParserStateObject.TryPrepareBuffer() |  
  |   | at Microsoft.Data.SqlClient.TdsParserStateObject.TryReadNetworkPacket() |  
  |   | at Microsoft.Data.SqlClient.TdsParserStateObject.ReadSniSyncOverAsync() |  
  |   | at Microsoft.Data.SqlClient.TdsParserStateObject.ReadSniError(TdsParserStateObject stateObj, UInt32 error) |  
  |   | at Microsoft.Data.SqlClient.TdsParserStateObject.ThrowExceptionAndWarning(Boolean callerHasConnectionLock, Boolean asyncClose) |  
  |   | at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose) |  
  |   | at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction) |  
  |   | ---> System.ComponentModel.Win32Exception (258): Unknown error 258 |  
  |   | Microsoft.Data.SqlClient.SqlException (0x80131904): Execution Timeout Expired.  The timeout period elapsed prior to completion of the operation or the server is not responding. |  
  |   | [19:48:11 ERR] An error occured during startup migration |  
  |   | [19:48:11 ERR] An error occurred using a transaction. |  
  |   | VALUES (N'20240104113247_JobsDescriptionLength', N'7.0.13'); |  
  |   | INSERT INTO [entity_framework].[__EFMigrationsHistory] ([MigrationId], [ProductVersion]) |  
  |   | [19:47:51 INF] Executed DbCommand (5ms) [Parameters=[], CommandType='Text', CommandTimeout='30'] |  
  |   | ALTER TABLE [jobs].[job] ALTER COLUMN [Description] nvarchar(3000) NOT NULL; |  
  |   | IF @var0 IS NOT NULL EXEC(N'ALTER TABLE [jobs].[job] DROP CONSTRAINT [' + @var0 + '];'); |  
  |   | WHERE ([d].[parent_object_id] = OBJECT_ID(N'[jobs].[job]') AND [c].[name] = N'Description'); |  
  |   | INNER JOIN [sys].[columns] [c] ON [d].[parent_column_id] = [c].[column_id] AND [d].[parent_object_id] = [c].[object_id] |  
  |   | FROM [sys].[default_constraints] [d] |  
  |   | SELECT @var0 = [d].[name] |  
  |   | DECLARE @var0 sysname; |  
  |   | [19:47:51 INF] Executed DbCommand (32ms) [Parameters=[], CommandType='Text', CommandTimeout='30'] |  
  |   | [19:47:51 INF] Applying migration '20240104113247_JobsDescriptionLength'. |  
  |   | ORDER BY [MigrationId]; |  
  |   | FROM [entity_framework].[__EFMigrationsHistory] |  
  |   | SELECT [MigrationId], [ProductVersion] |  
  |   | [19:47:51 INF] Executed DbCommand (4ms) [Parameters=[], CommandType='Text', CommandTimeout='30'] |  
  |   | SELECT OBJECT_ID(N'[entity_framework].[__EFMigrationsHistory]'); |  
  |   | [19:47:51 INF] Executed DbCommand (2ms) [Parameters=[], CommandType='Text', CommandTimeout='30'] |  
  |   | SELECT 1 |  
  |   | [19:47:51 INF] Executed DbCommand (2ms) [Parameters=[], CommandType='Text', CommandTimeout='30'] |  
  |   | SELECT OBJECT_ID(N'[entity_framework].[__EFMigrationsHistory]'); |  
  |   | [19:47:51 INF] Executed DbCommand (45ms) [Parameters=[], CommandType='Text', CommandTimeout='30'] |  
  |   | SELECT 1 |  
  |   | [19:47:50 INF] Executed DbCommand (59ms) [Parameters=[], CommandType='Text', CommandTimeout='30']

</body>
</html>

![image](https://github.com/ita-social-projects/StreetCode/assets/47561209/6d461ffe-25de-4725-9d72-025ff6ccf4df)

Stage VM resources at the same time when ALL requests fail to beckend(database is fully unaccessible):
![image](https://github.com/ita-social-projects/StreetCode/assets/47561209/f5c1ee6e-65fb-4131-9411-c697f6a726ed)

Errors on the Client after redeployment:
![image](https://github.com/ita-social-projects/StreetCode/assets/47561209/3f552514-b260-4420-9db7-da4765d62c4f)

**Comment by yaakymiv** [comment]
We resolved the issue with the restore of DB
