### ISSUE TITLE
Admin/Text and Video block

### ISSUE THREAD

**Issue by vladnvp** [ita-social-projects/StreetCode#122]
### Acceptance Criteria

1. Admin is able to enter "Заголовок"
2. Admin is able to enter "Основний текст". The area for text is resizable. 
3. Admin can apply basic formatting on text
4. Admin is able to add youtube.com link to "Відео", other links are not accepted
5. Admin is able to request video preview via the button

[Epic link](https://github.com/ita-social-projects/StreetCode/issues/114)

**Comment by vladnvp** [comment]
UPD
Admin is able to enter "Заголовок", **limit is 50 symbols**
Admin is able to enter "Основний текст". **Limit is 15 000 symbols**. The area for text is resizable.
Admin can apply basic formatting on text: **bold and italic.**

**Comment by AnastasiiaBdk** [comment]
What symbols can be entered into the fields was added.
The limit of symbols for the "Основний текст" field was changed (15000, not 25000).
For the acceptance criteria №5 was added the name of the button (according to the mock-up).
For the dictionary functionality was added clarification that this option is unavailable now, may be added in the future.

**Comment by mozhaieva** [comment]
6. The "Відео" field is inactive until the Admin fills in the "Заголовок" field.
