### ISSUE TITLE
Admin/Sources block

### ISSUE THREAD

**Issue by vladnvp** [ita-social-projects/StreetCode#125]
### Acceptance Criteria

1. Acceptance Criteria
Admin can add a new block via "+" button
1.1. System opens a modal window where an Admin can select a category from the available list and can enter available text
1.2. Admin can format Titles via click on corresponding buttons:
-Title 1 
-Title 2
1.3 Admin can add a hyperlink to a text
2. Admin can edit existing events via "pencil" icon
3. Admin can delete existing events via "trash" icon
4. All events are displayed as small blocks with titles on it

[Epic link](https://github.com/ita-social-projects/StreetCode/issues/114)

**Comment by iskoryk** [comment]
The category name is 23 symbols limit.
