### ISSUE TITLE
Admin/Art gallery block

### ISSUE THREAD

**Issue by vladnvp** [ita-social-projects/StreetCode#127]
### Acceptance Criteria

1. Admin can upload images
2. Images are displayed in the same way like it is working on user-facing StreetCode 
3. Admin can reorder images
4. Admin can add title and description to images
5. Admin can delete images

[Epic link](https://github.com/ita-social-projects/StreetCode/issues/114)

**Comment by vladnvp** [comment]
3. ~~Admin can reorder images~~ will not be implemented in MVP

**Comment by iskoryk** [comment]
Field Art Gallery consists of parts:
1. Завантажені арти - Admin can upload images
2. Шаблони - it is possible to choose exactly how the images will be displayed.
3. Попередній перегляд - Admin sees how images will be displayed from the user's side.
