### ISSUE TITLE
[Main StreetCode Block] [Audio button] The audio stops playing after the user switches to the new page of the website.

### ISSUE THREAD

**Issue by AlbinaVorobiova** [ita-social-projects/StreetCode#1286]
**Environment:** Windows 11 (64 bit), Google Chrome Version 122.0.6261.112 (Official build), (64 bit)
**Reproducible:** always
**Build found:** https://github.com/ita-social-projects/StreetCode/commit/aafbfbc286e9c0ae2ce12bbf8a259104b8edc3ac

**Priority:** High
**Severity:** Critical
**Type:** Functional

**Preconditions:**
1. The "Софія Яблонська" streetcode is created on the admin page. 
2. The audio is added to this streetcode.
3. The "Софія Яблонська" streetcode is opened on the stage. 

**Steps to reproduce:**
1. Click on the "Прослухати аудіо" button.
2. Click on the Play button of the audio player.
3. Click on the hamburger menu in the header.
4. Click on the "Головна" page.

**Actual result:**
- [ ] 1. The user can not listen to the audio while switching the website pages.
[Video of the bug](https://app.screencast.com/bSg08pogmsvlr?conversation=nUCsOd5LTR1rrkYGAy7uEj)
- [ ] 2. The "Аудіо на підході" button is displayed after loading the "Софія Яблонська" streetcode and switches to the "Прослухати текст" button only after 2 or 21 seconds. 
[Video of the bug](https://app.screencast.com/FnTiLtsVcvmNJ?conversation=zh3oR7TEnZGOq2vN022IHf) 

**Expected result:**
1. The user can listen to the audio while switching the website pages.
2. The "Прослухати текст" button is displayed at once after loading the "Софія Яблонська" streetcode.
![аудіо кнопка Яблонська](https://github.com/ita-social-projects/StreetCode/assets/160258291/cc0420a6-e5df-4a76-a527-5c8e8a983170)

Test Case: https://github.com/ita-social-projects/StreetCode/issues/72
User story: https://github.com/ita-social-projects/StreetCode/issues/20
Epic: https://github.com/ita-social-projects/StreetCode/issues/19

**Comment by arisssha** [comment]
The audio continues to stop after the user switches to another page on the website.
 Meanwhile, the 'Прослухати текст' button is displayed immediately after loading the 'Софія Яблонська' Streetcode.
