### ISSUE TITLE
[API][Chronology block] The chronology card is created with duplication of data from the already created chronology card in the fields: id, title, and description

### ISSUE THREAD

**Issue by iskoryk** [ita-social-projects/StreetCode#1323]
**Environment:** all
**Reproducible:** always
**Build found:** [a7d807f](https://github.com/ita-social-projects/StreetCode/commit/a7d807fdd928985083647a72ec61fa983110fea6)

**Preconditions**

1. Open Postman.
2. Choose the POST method.
3. Enter valid endpoints.

**Steps to reproduce**
1.1. Fill in all mandatory keys for creating Streetcode.
1.2. In "timelineItems" block enter keys "id", "title", "description" from the already created chronology card. For instance:
<details><summary>Details</summary>
<p>

"timelineItems": 
            "id": 1289,
            "title": "Номер один",
            "description": "На хуторі Вільховий Яр Харківської губернії у родині збіднілих дворян Грінченків народжується хлопчик Борис. Батько Дмитро походив з давнього козацького роду, а мати Поліксенія була донькою російського поміщика. Попри козацькі корені батька, вдома всі спілкувалися російською — українську батьки вважали «мужицькою». Як старший з п’яти дітей Борис змалечку навчається доглядати за молодшими.",

</p>
</details> 
1.3. Click the button Send.

2.1. Fill in all mandatory keys for updating Streetcode.
2.2. In "timelineItems" block enters the same data to the keys "id", "title", "description".
2.3. Click the button Send.

**Actual result**
1. Response - '200 OK'. Streetcode is published, and the duplicate of an already existing chronology card in the database is created.
2. Response - '200 OK'. Streetcode is published, and the duplicate of an already existing chronology card in this streetcode is created.
<img width="1914" alt="Screenshot 2024-03-29 at 10 58 40" src="https://github.com/ita-social-projects/StreetCode/assets/130586498/2d7e80e9-d5ff-4eb8-b959-71c738f8b035">

**Expected result**

1. The response returns a '400 Bad Request' status with the message 'Invalid timeline items id'. A "timelineitems id" must be unique for the entire database. While creating chronology card id=0.
3. The response returns a '400 Bad Request' status with the message 'Invalid title and description value'. The "title" and "description" must be unique for this Streetcode.

**Postconditions**
The bug is also reproduced if similar data is specified in separate requests. The "title" and "description" fields are also duplicated when updating the timeline block.

**User story:** #124

**Comment by sashapanasiuk5** [comment]
Its not a bug
