### ISSUE TITLE
[API] [Admin/StreetCode] It is impossible to transfer elements not required in the request body by using an empty array or null

### ISSUE THREAD

**Issue by SophiaMRI** [ita-social-projects/StreetCode#1332]
**Environment:** All
**Reproducible:** Always
**Build found:** [a7d807f](https://github.com/ita-social-projects/StreetCode/commit/a7d807fdd928985083647a72ec61fa983110fea6)

**Preconditions**
1. Open Postman.
2. Choose the POST/PUT method.
3. Enter valid endpoints.

**Steps to reproduce**
1. Enter the valid and required data in the body ("index", "streetcodeType", "title", "streetcodeType", "dateString", "eventStartOrPersonBirthDate", "teaser" and "imagesIds&imagesDetails", "status").
2. Leave all non-required fields empty - ([] and null key).
3. Click the 'Send' button.

**Actual result**
1. The response returns a '200 OK' status. 
2. The StreetCode has been created, but an 'Unexpected Application Error!' message appears on the front end.
3. The admin can't successfully create the StreetCode without the subtitles object (). 

https://github.com/ita-social-projects/StreetCode/assets/135108144/d673ae44-4a48-4269-bb99-2c554f0bef3a

![Стріткод  Історія на кожному кроці - Google Chrome](https://github.com/ita-social-projects/StreetCode/assets/135108144/c8df9274-feb3-45b9-a06e-d8fffbe56431)

https://github.com/ita-social-projects/StreetCode/assets/135108144/42d73261-4b19-46d4-820e-483928502c97

**Expected result**
1. The response returns a '200 OK' status.
2. The StreetCode has been created, and the front end has no errors.
3. The admin can successfully create a StreetCode with empty or null optional keys in the request body.

**Comment by mozhaieva** [comment]
The Streetcode has been created without without the subtitles object in the request body. The is no error on the front end side.
