### ISSUE TITLE
[API][Admin/New Streetcode] Fields Status, Alias, Sources during creation/update accept invalid data

### ISSUE THREAD

**Issue by iskoryk** [ita-social-projects/StreetCode#1338]
**Environment:** all
**Reproducible:** always
**Build found:** [a7d807f](https://github.com/ita-social-projects/StreetCode/commit/a7d807fdd928985083647a72ec61fa983110fea6)

**Preconditions**
1. Open Postman.
2. Choose the POST/PUT method.
3. Enter valid endpoints.
4. Check-in all mandatory keys for creating/updating Streetcode or Sources.

| Issue | Steps to reproduce | Actual result | Expected result | Status |
|--------|--------|--------|--------|--------|
| 1. Fields "Status" | 1. Enter:<br>1.1. -1,<br>1.2. <br>2. Click the button Send.  | '200 OK' Streetcode is created/updated with "Drafted" status. | The response returns a status of "400 Bad Request" with the message "The field "Status" can contain only 0, or 1, or 2. | Fail |
| 2. Fields "Alias/Короткий опис" | 1. Enter 50 characters.<br>2. Click the button Send.  | '200 OK' Streetcode is created/updated. | The response returns a status of "400 Bad Request" with the message "The field "Alias" can contain 33 characters or less". | Fail |
| 3. Fields "Sources" | 1. Enter 100 characters in the title key.<br>2. Click the button Send.  | '200 OK' status is created/updated. | The response returns a status of "400 Bad Request" with the message "The key "title" of Status can contain 23 characters or less". | Fail |
| 4. Fields "Sources" | 1. Enter 101 characters in the title key.<br>2. Click the button Send.  | '200 OK' but the new status is not displayed on the front end. | The response returns a status of "400 Bad Request" with the message "The key "title" of Status can contain 23 characters or less". | Fail |
<img width="644" alt="Screenshot 2024-04-03 at 11 56 15" src="https://github.com/ita-social-projects/StreetCode/assets/130586498/703c5b3a-c49b-4f8f-9da3-8f6322a2a051">

**User story**: #115, #125

**Comment by mozhaieva** [comment]
3,4. 'Sources' aren't created/updated with more then 23 characters -  "message": "Title cannot be longer than 23 characters." - 400 Bad request

**Comment by sashapanasiuk5** [comment]
Fixed in https://github.com/ita-social-projects/StreetCode/issues/308
