### ISSUE TITLE
[Page UP and donate button] [Fuctional] [Desktop] The Up button is shown up on the second screen

### ISSUE THREAD

**Issue by BDaria** [ita-social-projects/StreetCode#1341]
**Environment:** Windows 11, Chrome, 123.0.6312.59 (64 bit), screen resolutions: 1280x1024, 1024x768, 800x600.
**Reproducible:** always.
**Build found:** https://github.com/ita-social-projects/StreetCode/commit/a7d807fdd928985083647a72ec61fa983110fea6

**Preconditions**
Open any Streetcode.

**Steps to reproduce**
1. Choose resolution 1280x1024.
2. Scroll down to the second screen.
3. Pay attention to the UP button appearance. 

**Actual result**
The Up button is shown up on the second screen.

https://github.com/ita-social-projects/StreetCode/assets/86358268/ee913ee5-236f-4a57-98ba-46a8d24f6ea8

**Expected result**
The Up button is shown up after the second screen (Text and video block). 

**User story and test case links**
User story #78 #24   
Test case #93

**Comment by DDeviak** [comment]
It is not considered a bug
