### ISSUE TITLE
Partners

### ISSUE THREAD

**Issue by vladnvp** [ita-social-projects/StreetCode#136]
**As a** user **I want to** to see all Partners on one page

### Acceptance Criteria 1
1. User is able to open this page by clicking on a button in the footer "Партнери"
2. Page is optimized for desktop and mobile devices and prepared according to design
3. There 2 blocks of partners with different sizes of images on a page
Bigger for main partners
Smaller for small partners
4. Hover over an image opens a pop-up with detailed information about Partner (please, validate animation with Figma)
5. User is able to open "Quick donate" window via click in button "Задонатити"
6. "Стати партнером" button is displayed and click on it opens a modal window (Acceptance Criteria 2)
7. Another "Стати партнером" button is floating at the bottom of a screen and click on it opens a modal window

### Acceptance Criteria 2 - Стати партнером window
1. User is allowed to submit form only if at lease 1 symbol is entered
2. Email field is mandatory
3. User is able to close modal window via X button (not presented on design)
4. After the form was submitted - an email should be initiated to streetcodeua@gmail.com

**Example:**
Тема: Статс партнером
Лист: 
Контакний імейл - human@gmail.com
Текст: Можу допомагати друкуавти таблички на 3Д принтері

**Notes:**
Please, keep in mind that in future releases text on this page will be editable via admin panel
"Tt" button on mobile adaptive which stands for change of text size will be added later

[Link to approved design in Figma](https://www.figma.com/file/9ydz23Y1yKPGx92lsqBhak/StreetCode?node-id=3160%3A4206&t=DxT7cJbPTGVxmrH4-1)

[Epic link](https://github.com/ita-social-projects/StreetCode/issues/138)

**Comment by Mariya2708** [comment]
Acceptance Criteria 1
5. User is able to open "Підтримай проєкт" modal window via click on the button "Задонатити" at the bottom of the page (Acceptance Criteria 3)

Acceptance Criteria 3 - Підтримай проєкт modal window
1. Modal window "Підтримай проєкт" looks according to the Figma mockup.
2. User is able to enter the donation amount or select it by clicking buttons with certain sum '50', '100' or '500'
3. In hovered state the button with the donation amount is red.
4. After entering a donation amount equal to the amount shown on the button, the button turns red
5. The "Підтримати" button is disabled (it's grey) until the user enters the donation amount and agree to the processing of personal data.
6. Clicking on the active "Підтримати" button (it's red) opens the payment page in a new browser tab.
7. Clicking on the 'персональних даних' link opens page "Політика конфіденційності".
8. User is able to close the modal window by clicking on the X button or outside the window .

**Comment by ulyarka74** [comment]
Acceptance Criteria 1
User is able to open this page by clicking on a button in the footer "Партнери" or using "Burger" button  changed to 
 User is able to open this page by clicking on a button in the footer "Партнери" or  clicking on the "Партнери" button  in the  "Burger" menu or user can see this block "Наші партнери" (short version) by scrolling down main page.

**Comment by ulyarka74** [comment]
Acceptance Criteria 1
2.  Page is optimized for desktop and mobile devices and prepared according to design changed to 
The layout of the page must be adaptive: desktop( 1920 px, 1600 px, 1025 px), tablet( 768 px), mobil (360 px).
6. "Стати партнером" button is displayed and click on it opens a modal window (Acceptance Criteria 2) changed to 
 User is able to open "Стати партнером" in modal window (Acceptance Criteria 2) by clicking on the "Долучитися" button in the header (desktop) or by clicking the "Стати партнером" button at the bottom of the"Партнери" page.

**Comment by Nikita3301** [comment]
**ADDED**
**Description**
This page will allow users to discover all information about project partners, in other words, people who support the project. They will also be able to donate or offer cooperation options to became a partner.

**UPDATE** to Acceptance Criteria 2 - A modal window Стати партнером:
**OLD**
2. Email field is mandatory
**NEW**
2. All fields in the modal window are mandatory and marked with asterisk (*), verify their location in Figma
3. The email must follow a standard email format (e.g. user@example.com).

**UPDATE** to Letter example:
Тема: “Стати партнером”
Контакний email: human@gmail.com
Текст: “Можу допомагати друкувати таблички на 3Д принтері”

**Comment by Sandr89** [comment]
**ADDED** to Acceptance criteria 1 
3.Main partners(with bigger pop-ups) have to be displayed first in seperate block. Small partners(with smaller pop-ups) have to be displayed below main partners in separate block.

**ADDED** to Acceptance criteria 2 - Стати партнером window
6.User is not able to send more than 3 forms in 5 minutes

**UPDATE** to Acceptance criteria 1
**OLD**
7.Another "Стати партнером" button is floating at the bottom of a screen and click on it opens a modal window
**NEW**
7.Another "Стати партнером" button is floating at the bottom right corner of a screen and click on it opens a modal window. This button is statically pinned on the screen until user scrols to the footer. When "Стати партнером" button reaches footer it should unpin and continue to move with the whole page if user proceeds to scroll till the end of the page.

**Comment by OlenkaKyrychenko** [comment]
Acceptance criteria 'User is able to close modal window via X button (not presented on design)'
is changed to 'User is able to close the modal window via X button or by clicking outside the window.'

Acceptance Criteria 2 'After the form was submitted - an email should be initiated to streetcodeua@gmail.com'
is changed to 'After the form was submitted, an email should be initiated to streetcodeua@gmail.com in the stage environment.'

Added to Acceptance Criteria 2
Validation messages appear when the user enters invalid data or leaves fields empty.
The Captcha is displayed in the modal window.
After the user sent 3 consecutive messages, the 'Відправити' button is disabled for 5 minutes and the 'Ви зможете повторити наступну спробу через 5 хвилин' message appears top of the page.
After clicking on the 'Відправити' button, the modal window is closed.

Edited Acceptance Criteria 2 'User is not able to send more than 3 forms in 5 minutes' to 'User with one IP address is not able to send more than 3 forms in 5 minutes.'

**Comment by Ann02** [comment]
**ADDED** to Acceptance criteria 1
- Main partners have a larger logo size and are shown first, look according to the mockup(figma). On the computer, 3 logos are placed in one row. On the tablet, 2 logos are placed in one row. On the phone, 1 logo is placed in one row.
- Secondary partners have a smaller logo size and are shown after main partners, look according to the mockup(figma). On the computer, 6 logos are placed in one row. On the tablet, 4 logos are placed in one row. On the phone, 2 logo is placed in one row.

**ADDED** to Acceptance criteria 2
2. The text field accepts alphabet letters, special charachers, numbers.
3. User is allowed to enter up to 500 characters in the text field.
4. The placeholders for all fields are shown, look according to the mockup(figma).
