### ISSUE TITLE
[API][Audio] Response to GetAll request take too much time

### ISSUE THREAD

**Issue by iskoryk** [ita-social-projects/StreetCode#1365]
**Environment:** all
**Reproducible:** always
**Build found:** [a7d807f](https://github.com/ita-social-projects/StreetCode/commit/a7d807fdd928985083647a72ec61fa983110fea6)

**Preconditions**

1. Open Postman.

**Steps to reproduce**
1. Choose the GET method.
2. Enter valid endpoints and /Audio/GetAll.

**Actual result**
The response is 200 OK, the data is displayed, the response took 8.40 seconds, but there are only 2 audios in the database.

**Expected result**
The response is 200 OK, the data is displayed, if there are only 2 audio in the base, the response should take 1 second.

**User story:** #115 

<img width="694" alt="Screenshot 2024-04-12 at 19 38 42" src="https://github.com/ita-social-projects/StreetCode/assets/130586498/a03ba770-f344-4f24-b8ea-4a18aa9c9092">

**Comment by mozhaieva** [comment]
![Image](https://github.com/user-attachments/assets/b2888796-2b49-4cce-916c-d4f954d2d8eb)

**Comment by mozhaieva** [comment]
It's not a bug.
