### ISSUE TITLE
[Instagram block] The post image does not match the pixel size of the mockup

### ISSUE THREAD

**Issue by Tetiana1202** [ita-social-projects/StreetCode#1414]
**Environment:** macOS 13.6.6 (22G630), Google Chrome  124.0.6367.60
**Reproducible:** always
**Build found:** 79fb490

**Preconditions**
1. Open mockup: https://www.figma.com/file/9ydz23Y1yKPGx92lsqBhak/StreetCode?type=design&node-id=7979-12567&mode=design&t=XkzzQErTLWLiFUwn-0 (desktop)
2. Open: https://stage.streetcode.com.ua

**Steps to reproduce**
1. Scroll to Instagram block
2. Open the tool 'DevTools'
3. Hover over the image of any post
4. Check the number of pixels in the image
5. Check the number of pixels in the image of the post on the mockup

**Actual result**
1. The site displays 300x300 pixel images

**Expected result**
1. The mockup shows the pixels in the 300x299 image

User story #698

**Comment by sashapanasiuk5** [comment]
won't fix
