### ISSUE TITLE
[UI/Streetcode page/Art gallery] [Desktop] The images' sizes do not correspond the mockup in the Art gallery

### ISSUE THREAD

**Issue by BDaria** [ita-social-projects/StreetCode#1437]
**Environment:** Windows, Chrome, 124.0.6367.119.
**Reproducible:** always
**Build found:** https://github.com/ita-social-projects/StreetCode/commit/79fb4900bc472c7efaf3e92e659797ccf1273ce6

**Preconditions**
1. Open the Admin page.
2. Create a new Streetcode.
3. Add images to the Art Gallery.
4. Save the Streetcode.
5. Open the created Streetcode as a user.

**Steps to reproduce**
1. Go to the Art Gallery.
2. Pay attention to the image sizes on each slide.

| #| Images number and shape  | Expected result | Actual result |
|--------|--------|--------|--------|
| 1 |![art_gallery100](https://github.com/ita-social-projects/StreetCode/assets/86358268/669f31a0-0a1b-4bf7-8924-10af9d1cfb0f) | 806x536 | 770x536 (resolution1025-1200), 806x536 (resolution1201-1920)|
| 2 | ![art_gallery100 (2)](https://github.com/ita-social-projects/StreetCode/assets/86358268/83a72790-ea29-4c0d-8bd4-85fb249396f8) | 790x536 / 380x536 | 503,33x536 / 236,67x536  (resolution 1025-1200), 647,33x536/308,66x536 (resolution 1201-1450), 790x536 / 380x536( resolution 1451-1920) |
| 3 | ![art_gallery100 (3)](https://github.com/ita-social-projects/StreetCode/assets/86358268/1c619e5d-f5c5-4a0d-a864-36e6f3946ea7) | 790x536 / 380x253 | 503.33x536 / 236.67x253(resolution 1025-1200), 647,33x536/308,66x253 (resolution 1201-1450), 790x536 /380x253 (resolution1451-1920) |
| 4 | ![art_gallery100 (4)](https://github.com/ita-social-projects/StreetCode/assets/86358268/ceacb3a1-aa44-4a48-b667-1e609c88957b) | 380x536 | 236.67x536 (resolution1025-1200), 308,67x536 (resolution 1201-1450), 380x536 (resolution 1451-1920)|
| 5 |![art_gallery100 (6)](https://github.com/ita-social-projects/StreetCode/assets/86358268/17ea8ed1-8ce2-44ac-bb4e-0b633392b935) | 380x536 / 380x253 | 236,66x536/236,67x253  (resolution 1025-1200) 308.67x536 / 308.67x253 (resolution 1201-1450), 380x536 / 380x253 (resolution 1451-1920) | 
| 6 | ![art_gallery100 (7)](https://github.com/ita-social-projects/StreetCode/assets/86358268/fdd747e4-6330-40bb-b5b9-02bc5d8801e2) | 380x253 / 380x536 | 236,66x253/236,67x536  (resolution 1025-1200) 308.66x253/308.67x536 (resolution 1201-1450),  380x253 / 380x536 (resolution 1451-1920) |
| 7 | ![art_gallery100 (8)](https://github.com/ita-social-projects/StreetCode/assets/86358268/d25946cf-4916-4848-85e4-c330f0364199) | 380x253 / 380x536 | 236,66x253/236,67x536 (resolution 1025-1200) 308.66x253/308.67x536 (resolution 1201-1450), 380x253 / 380x536( resolution 1451-1920) |
| 8 | ![art_gallery100 (9)](https://github.com/ita-social-projects/StreetCode/assets/86358268/1e2ef4e4-4c06-47ec-a3ce-9d8eb4690efd) | 380x253 / 380x536 | 236,66x253/236,67x536 (resolution 1025-1200) 308.66x253/308.67x536 (resolution1201-1450), 380x253 / 380x536 (resolution 1451-1920) |
| 9 | ![art_gallery100 (10)](https://github.com/ita-social-projects/StreetCode/assets/86358268/170b6583-510e-4ed5-bdd6-8c2c37fd22a0) | 380x253 | 236,66x253 (resolution 1025-1200) 308.66x253( resolution1201-1450), 380x253 (resolution 1451-1920) | 
| 10 | ![art_gallery100 (11)](https://github.com/ita-social-projects/StreetCode/assets/86358268/301c9888-3115-42cb-8714-55aff3a4d52f) | 380x253 | 236,66x253 (resolution 1025-1200) 308.66x253 (resolution 1201-1450), 380x253 (resolution 1451-1920) |

**User story and test case links**
User story #75
Test case #1297

**Comment by Shossy** [comment]
fixed issues with 3 first templates. Other templates mentioned there were ok since it's part of responsive design on smaller screen sizes
