### ISSUE TITLE
[Carousel Streetcodes/Main page] Not 10 last added streetcodes are displayed in the Carousel Streetcodes block

### ISSUE THREAD

**Issue by ChornaOksana** [ita-social-projects/StreetCode#1456]
**Environment:** Windows 10 Home, Google Chrome122.0.6261.129 (64 bit)
**Reproducible:** always
**Build found:** [79fb490](https://github.com/ita-social-projects/StreetCode/commit/79fb4900bc472c7efaf3e92e659797ccf1273ce6)
Priority: high
Severity: major

**Preconditions**
More than 11 streetcodes are added

**Steps to reproduce**
1. Go to Main page
3. Scroll down to Carousel streetcodes block
4. Go to Admin panel
5. Open "Стріткоди" page
6. Compare all shown Streetcodes on the Main page with 10 lastly added Streetcodes on Admin page

**Actual result**
User can see 10 randomly Streetcodes on the Carousel streetcodes block

**Expected result**
User can see 10 lastly added Streetcodes on the carousel Streetcodes block

**User story** #701

**Comment by SophiaMRI** [comment]
Duplicate - Actual Bag report -> #992
