### ISSUE TITLE
[StreetCode page] [UI] The tags are not displayed in the cards under the images in the "Зв'язки з історією" block

### ISSUE THREAD

**Issue by Kira2987** [ita-social-projects/StreetCode#1747]
Environment: all devices
Reproducible: always

Preconditions:
The "Стріткоди" page is open

Steps to reproduce:

1. Select one of the streetcodes and click on it ("[Михайло Грушевський](https://stage.streetcode.com.ua/mykhailo-hrushevskyi)").
2. Scroll down to the "Зв'язки з історією" block.
3. Hover over each streetcode card located in block and observe the presence of tags under the image.
4. Repeat 1, 2. 3 steps with all streetcodes.
5. Check whether joint tags of the "Зв'язки з історією" block and tags of main streetcode opened page are displayed in the cards of the block.

https://github.com/user-attachments/assets/2e6af15b-8295-4b85-ae09-cd0f77a84dff

Actual result:
1-3. On the "Михайло Грушевський" page in the "Зв'язки з історією" block "[Казимир Малевич](https://stage.streetcode.com.ua/kazymyr-malevych)" card doesn't have any tags.
4-5. If only one tag from the streetcode opened page is joint with card in "Зв'язки з історією block" - it does not appear under the image on the card.

Expected result:
Joint tags appear in the card regardless of quantity.

**Comment by YuliiaAndreieva** [comment]
Was fixed in [1479](https://github.com/ita-social-projects/StreetCode_Client/pull/1479)
