### ISSUE TITLE
[Technical Task] Refactoring RelatedFigures block on Streetcode page

### ISSUE THREAD

**Issue by ilko-dev** [ita-social-projects/StreetCode#1848]
### Brief overview
Refactoring RelatedFigures and RelatedFigureItem components, RelatedFiguresModals  to use a common store for saving common tags and optimizing logic to avoid redundant API requests.

**Comment by YuliiaAndreieva** [comment]
Was completed in [1479](https://github.com/ita-social-projects/StreetCode_Client/pull/1479)
