### ISSUE TITLE
Main StreetCode block

### ISSUE THREAD

**Issue by vladnvp** [ita-social-projects/StreetCode#20]
**As a user I want to see concise information at the top of the page so I will be able to get acquainted quickly with a person/event**

**Description**
The main block of information about a person or event. This block will provide short information about event/person and will allow to listen to a text or use AR in Instagram (upon availability)

### Acceptance Criteria
1. Background image is applied for this block on a page.
![image](https://user-images.githubusercontent.com/112704799/208943773-5f233ea0-f7bd-4626-ab29-279fbbfde506.png)
2. Animated image is displayed and it starts automatically and stops after 1 playback
The user is able to switch to another image using squares (black/white image and colored)
The dimensions are proportional to the fields of the picture - 190x165
3. "Стріткоди" + Full StreetCode name is displayed
![image](https://user-images.githubusercontent.com/112704799/210261851-b1dbb2a3-7aff-46ba-9f52-221a98148f0a.png)
4. "Streetcode number" is displayed
5. "Name of a person or event" is displayed
6. "Years of life / Date or period" of the event
![image](https://user-images.githubusercontent.com/112704799/208943019-3c59bbd4-f39e-4751-aef1-8e18e648e7e7.png)
7. "Tags are displayed" and clicking on them opens a modal window with all StreetCodes with this tag.
8. "Teaser" is displayed
No more than 400 symbols including spaces if there is 1 paragraph
OR
No more than 400 symbols including spaces if there are 2 paragraphs
![image](https://user-images.githubusercontent.com/112704799/208943653-585d65e7-aa95-4680-9e13-0acab127c132.png)
9. "Прослухати текст" button is displayed upon the availability of the audio record and clicking on a button initiates a start of an audio, which has a voice recording of text displayed in teaser 
A player should be pinned to the bottom of the screen, only 1 button is available at the same time. "Play" if record was not played, "pause" if record is playing. After playback of a recording button returns to "Play", providing the user an ability to play record again.
9.1. If an audio record for the teaser is not available - "Прослухати текст" button is inactive and the text on it is changed to "Аудіо на підході"
![image](https://user-images.githubusercontent.com/112704799/211647900-76799a29-a470-4768-b11f-90f27eafa332.png)
10. "Оживити картинку" button is displayed upon the availability of the AR item 
> On Desktop should move user to the bottom of the page to block "AR Instagram"
> On Mobile should move user to Instagram app with this effect
![image](https://user-images.githubusercontent.com/112704799/208946064-c413a080-9741-43c6-9efc-35148245aa92.png)
11. Donate button is displayed and pinned to the screen's bottom right side. Click on it opens a modal window with a donation option.

**Epic link**
[(Epic) StreetCode page](https://github.com/ita-social-projects/StreetCode/issues/19)

**Comment by vladnvp** [comment]
UPD to acceptance criteria
2. Animated image is displayed **and is starts automatically and stops after 1 playback**
3. ~~"Стріткоди" + Last name of a person is displayed~~ "Стріткоди" + Full StreetCode name is displayed
![image](https://user-images.githubusercontent.com/112704799/210261851-b1dbb2a3-7aff-46ba-9f52-221a98148f0a.png)
7. "Tags are displayed" and clicking on them opens a modal window **with all StreetCodes with this tag.**

**Comment by vladnvp** [comment]
UPD to acceptance criteria
2. Animated image is displayed and is starts automatically and stops after 1 playback
**The user is able to switch to another image using squares (black/white image and colored)
The dimensions are proportional to the fields of the picture - 190x165**
9. "Прослухати текст" button is displayed upon the availability of the audio record and clicking on a button initiates a start of an audio **and player should be pinned to the bottom of the screen**

**Comment by vladnvp** [comment]
UPD to acceptance criteria
8. "Teaser" is displayed ~~(no more than 300 symbols including spaces)~~ 
No more than 400 symbols including spaces if there is 1 paragraph
OR
No more than 400 symbols including spaces if there are 2 paragraphs

**Comment by vladnvp** [comment]
UPD to acceptance criteria
(NEW)
9.1. If an audio record for the teaser is not available - "Прослухати текст" button is inactive and the text on it is changed to "Аудіо на підході"

**Comment by vladnvp** [comment]
UPD
No more than ~~400~~ 520 symbols including spaces if there is 1 paragraph
OR
No more than ~~400~~ 455 symbols including spaces if there are 2 paragraphs

**Comment by kikimou** [comment]
UPD
2. ~~The user is able to switch to another image using squares (black/white image and colored)~~ The user is able to switch to another image using squares or by clicking on the right/left area of the picture (black/white image and colored)
~~The dimensions are proportional to the fields of the picture - 190x165~~

**Comment by kikimou** [comment]
UPD
3. ~~"Стріткоди" + Full StreetCode name is displayed~~ 
"Стріткоди" + Full StreetCode name is displayed
> Clicking on the "Стріткоди" will redirect user to the Catalog page

**Comment by kikimou** [comment]
UPD
~~ 7. "Tags are displayed" and clicking on them opens a modal window with all StreetCodes with this tag~~ 
7. "Tags are displayed" and clicking on them opens a modal window with all StreetCodes with this tag (temporarily only on Desktop)

**Comment by kikimou** [comment]
UPD
~~8. "Teaser" is displayed
No more than 520 symbols including spaces if there is 1 paragraph
OR
No more than 455 symbols including spaces if there are 2 paragraphs
![image](https://user-images.githubusercontent.com/112704799/208943653-585d65e7-aa95-4680-9e13-0acab127c132.png)~~

8. "Teaser" is displayed
8.1. If there is not enough space in the block the end of the text hides under the button "Прослухати текст" so user is able to scroll it
![image](https://github.com/ita-social-projects/StreetCode/assets/83531484/3b33007a-5b06-4237-ae25-2106eb8d247c)

**Comment by kikimou** [comment]
UPD
~~10. "Оживити картинку" button is displayed upon the availability of the AR item 
> On Desktop should move user to the bottom of the page to block "AR Instagram"
> On Mobile should move user to Instagram app with this effect
[image](https://user-images.githubusercontent.com/112704799/208946064-c413a080-9741-43c6-9efc-35148245aa92.png)~~

10. "Оживити картинку" button is displayed upon the availability of the AR item only on Desktop
10.1. Clicking on the button should move the user to block "AR Instagram"
![image](https://github.com/ita-social-projects/StreetCode/assets/83531484/1dd5391e-c833-46bf-be3e-6aeb5b8262ee)

**Comment by AlbinaVorobiova** [comment]
UPD to acceptance criteria
2. Animated image is displayed and is starts automatically and stops after 1 playback
The user is able to switch to another image using squares (black/white image and colored)
The dimensions are proportional to the fields of the picture - 190x165

What is wrong? According to the Mockup, the dimensions of the animated picture are **415х542 px.**

**NEW:**
2. Animated image is displayed and it starts automatically and stops after 1 playback
2.1. The user can switch to another image using squares (black/white image or colored)
The dimensions of the animated picture are proportional to the fields of the picture: 415х542 px

**Comment by AlbinaVorobiova** [comment]
**UPDATE to acceptance criteria:**
9.  "Прослухати текст" button is displayed upon the availability of the audio record and clicking on a button initiates a start of an audio, which has a voice recording of text displayed in the teaser
9.1. The user can listen to the audio and use the site at the same time
9.2. The player is pinned to the bottom of the screen, only 1 button is available at the same time. "Play" if record was not played, "Pause" if record is playing. After playback of a recording button returns to "Play", providing the user an ability to play record again.
9.3. If an audio record for the teaser is not available, "Прослухати текст" button is inactive and the text on it is changed to "Аудіо на підході"
9.4. Regardless of the active browser tab or window of the system, the audio shouldn't stop

**What was wrong?**
The 9.2 and 9.4 items should become more understandable and readable (according to the requirements)   

**NEW acceptance criteria:**
9. "Прослухати текст" button is displayed upon the availability of the audio record and clicking on a button initiates a start of an audio, which has a voice recording of text displayed in the teaser
9.1. The user can listen to the audio and use the site at the same time
9.2. The player is pinned to the bottom of the screen. Only 1 button is available at the same time:
-"Play" button (if the record is not played)
OR
-"Pause" button (if the record is playing)
When the audio recording has finished the playback, the "Pause" button returns to "Play" and provides the user the ability to play the record again.
9.3. If the audio record for the teaser is not available, "Прослухати текст" button is inactive and the text on it is changed to "Аудіо на підході" button
9.4. If the user turns on the audio recording and collapses the active browser tab/tabs or window of the system, the audio recording shouldn`t stop

**Comment by AlbinaVorobiova** [comment]
**UPDATE to acceptance criteria:**
8. "Teaser" is displayed
8.1. If there is not enough space in the block the end of the text hides under the button "Прослухати текст" so user is able to scroll it

**What was wrong?**
The important information (about the length of the teaser) was written as a new comment (vladnvp commented on Jun 23, 2023): 
8. "Teaser" is displayed 
(No more than 520 symbols including spaces if there is 1 paragraph
OR
No more than 455 symbols including spaces if there are 2 paragraphs)
**! But it was not duplicated to the 8 item of the whole acceptance criteria`s description**.

**NEW acceptance criteria:**
8. The "Teaser" is displayed
8.1. If there is not enough space in the block, the end of the text hides under the "Прослухати текст" button so the user can scroll it.
8.2. The maximum length of the teaser:
No more than 520 symbols including spaces if there is 1 paragraph
OR
No more than 455 symbols including spaces if there are 2 paragraphs

**Comment by AlbinaVorobiova** [comment]
**UPDATE to acceptance criteria:**
11. Donate button is displayed and pinned to the screen's bottom right side. Click on it opens a modal window with a donation option.

**What was wrong?**
1) This button is named "Задонатити" (according to the Mockup)
2) "Click on it opens" phrase is not correct   

**NEW acceptance criteria:**
"Задонатити" button is displayed and pinned to the screen's bottom right side. Clicking on it opens a modal window with a donation option.

**Comment by AlbinaVorobiova** [comment]
**UPDATE to acceptance criteria:**
12. Page Up button is displayed and pinned to the screen's bottom right side. Click on it scroll the page to the main streetcode block.

**What was wrong?**
"Click on it scroll" phrase is not correct

**NEW acceptance criteria:**
The Page Up button is displayed and pinned to the screen's bottom right side. Clicking on it scrolls the page to the main streetcode block.

**Comment by AlbinaVorobiova** [comment]
**NEW:**
The new item is added to the acceptance criteria:
10.2. The "Оживити картинку" button is not displayed on the tablet and mobile versions.

**Comment by AlbinaVorobiova** [comment]
**UPDATE to acceptance criteria:**
The "Оживити картинку" button is displayed upon the availability of the AR item only on Desktop.
10.1. Clicking on the button should move the user to block "AR Instagram".
![Опис 10 пункту юзер сторі (кнопка Оживити картинку)](https://github.com/ita-social-projects/StreetCode/assets/160258291/78e924d2-3863-4fe7-a174-8f2bd3244125)

10.2. The "Оживити картинку" button is not displayed on the tablet and mobile versions.

**NEW:**
The "Оживити картинку" button should be removed (according to the Customer`s requirement).

**Comment by AlbinaVorobiova** [comment]
**NEW item:**
11. The layout of the StreetCode page must be adaptive: desktop (1920px, 1600px, 1025px), tablet (768px), mobile (360px).
