### ISSUE TITLE
Interesting facts block

### ISSUE THREAD

**Issue by vladnvp** [ita-social-projects/StreetCode#26]
**As a user I would like to see several interesting facts about a person/event so I will know more about it**

**Description**
This block will allow to user to view interesting facts about a person/event

### Acceptance Criteria
1. Title "Цікаві факти" is displayed
2. Interesting fact contains an image, title, and text no more than 300 symbols including spaces)
3. 3 interesting facts are displayed at the same time
4. If there are more than 300 symbols including spaces - "Трохи ще" button appears under the text and click on it opens a modal window to fit all available text. Only clicking on this button opens a modal window.
5. Quantity of items in the progress bar at the bottom matches the number of interesting facts
6. Progress bar matches the sequence of a fact displayed in the front
7. If more than 1 fact is available navigation arrows are displayed and a click on them moves on 1 fact forward or back. 
![image](https://user-images.githubusercontent.com/112704799/209190162-f2cc21ae-6fc2-43de-b2a3-d3e6e8ac3c1a.png)
8. If only one fact is displayed - it is located in the centre of block
9. If only two facts are displayed - then one fact (chosen) in the center, and before and after it - doubled second fact
10. If there are 3 or more facts displayed - just scroll through in a loop
11. Сlicking on previous/next facts moves facts cards and moves clicked one to the front
12. Facts cards must be looped.

**Epic link**
[(Epic) StreetCode page](https://github.com/ita-social-projects/StreetCode/issues/19)

**Comment by vladnvp** [comment]
UPD to acceptance criteria
1. Title "Цікаві факти" was changed to "Wow-факти"
![image](https://user-images.githubusercontent.com/112704799/210258883-4ff917a0-a1c9-4b84-9eb6-44d7dd9052e4.png)

**Comment by vladnvp** [comment]
UPD to acceptance criteria
4. If there are more than 300 symbols including spaces - "Трохи ще" button appears under the text and clicking on it opens a **modal window to fit all available text. Only click on this button opens a modal window.**
(NEW) 
8. If only one fact is displayed - it is located in the centre of block
9. If only two facts are displayed - then one fact (chosen) in the center, and before and after it - doubled second fact
10. If there are 3 or more facts displayed - just scroll through in a loop
11. Сlicking on previous/next facts moves facts cards and moves clicked one to the front
12. Facts cards must be looped.

**Comment by vladnvp** [comment]
UPD:
4. If there are more than ~~300~~ 250 symbols including spaces - "Трохи ще" button appears under the text and click on it opens a modal window to fit all available text. Only clicking on this button opens a modal window.
2. Interesting fact contains an image, title **(no more than 68 symbols including spaces)**, and text no more than 600 symbols including spaces)

**Comment by ChornaOksana** [comment]
UPD to Acceptance Criteria:
10. If only two facts are displayed - then one fact (chosen) in the center, and before and after it - doubled second fact, **cards must be looped.**
14. Every card has a short description (hint) of photo, its author or/and source. It`s located on the bottom of the photo. Hint is displayed when the card is chosen. Text disappears in 4 seconds and displays again when user hover over the photo.

**Comment by AlbinaVorobiova** [comment]
**NEW item:**
15. The layout of the StreetCode page must be adaptive: desktop (1920px, 1600px, 1025px), tablet (768px), mobile (360px).

**Comment by ChornaOksana** [comment]
UPD:
6. If more than 1 fact is available the navigation indicators are displayed and are changing according to selected cards.
The term "progress bar" was changed onto "navigation indicators"
