### ISSUE TITLE
Implement Request Response Middleware

### ISSUE THREAD

**Issue by wehfis** [ita-social-projects/StreetCode#275]
**As a** product owner **I want to**  add request response middleware **so that** we have more logs.

**Description**
We want to add request response middleware to log each request and response send to and from the application. We also should have the possibility to add exceptions (register routes which we want to ignore in request response middleware logging) and to be able to mask some sensitive information(passwords, tokens and so on). So we need a solution which logs everything and gives us an opportunity to manually configure logging of some specific routes or models in that routes.

The following steps must be completed as part of this ticket:

- Add request response middleware with extention method to register it.
- Modify request response middleware to include filtering of registered exception rules(can be classes with some propetries which identifies what to filter)
- Logs should be structured and written by Serilog

### Acceptance Criteria

- All requests and responses are logged to console;
- Registered paths to ignore are ignored;
- Registered properties of specific models to ignore are ignored;

**Epic link**
E.g.: Epic #100 [Epic](https://jira.softserve.academy/browse/100)

**Labels to be added**
"User story", Correspondind Functionality (e.g. User), Priority ("pri: "), "Corresponding Epic"

### Tasks 
1. - [ ] Development
2. - [ ] Unit tests
3. - [ ] Documentation
4. - [ ] QA

**Comment by LanchevychMaxym** [comment]
Also as part of this ticket lets add ignoring the Health check routes and mask the password property from the authentication calls.
