### ISSUE TITLE
CORS configuration

### ISSUE THREAD

**Issue by MariaPadalka** [ita-social-projects/StreetCode#290]
**As a** <role> **I want to** <....> **so that** <...>

**Description**
Put the cors configuration into appsettings.json to change the settings directly in the file, and not in the code. Accordingly, change the code and test the result by entering various parameters

### Acceptance Criteria
Changing the links in appsettings.ison should change the access parameters on the site. 
There shuldn't be this error "Redirect has been blocked by CORS policy".

**Comment by DanyilTerentiev** [comment]
Please, fill the description section properly
