### ISSUE TITLE
[Main StreetCode block] Verify that the "Оживити картинку" button is clickable upon the availability of the AR item (on the desktop).

### ISSUE THREAD

**Issue by DariaAntonenko** [ita-social-projects/StreetCode#331]
**Priority: high**

**Description:**
The test case verifies that the "Оживити картинку" button is clickable upon the availability of the AR item (on the desktop).

**Preconditions:**
 1. The "StreetCode" page is opened.

**Steps to reproduce:**
 1. Click on the "Оживити картинку" button. 
 2. Verify that the page will scroll to the AR item.

**Expected result:**
The page automatically scrolls to the section "AR-історія в Інсті!" and the user can see the QR code.  

![AR-історія в Інсті](https://github.com/ita-social-projects/StreetCode/assets/160258291/7a1d54de-c3e8-4385-82fc-a6a5e78864ef)

User story:https://github.com/ita-social-projects/StreetCode/issues/20
Epic: https://github.com/ita-social-projects/StreetCode/issues/19

**Comment by AlbinaVorobiova** [comment]
**UPDATE to:**
**Description:**
Test case verifies working of "Оживити картинку" button on desktop and mobile version

**Preconditions**
Go to the “StreetCode” page

**Steps to reproduce**
Click on "Оживити картинку" button

**Expected result**
On Desktop user automatically goes to the end of the page to the section "Грай з AR в Instagram"

**What was wrong?**
1. According to the requirements, this button should be in the desktop version and not in the mobile version. The presence/absence of the button was already checked in the [UI] test case.
2. The test case`s title should be renamed.
3. Expected result was written incorrectly and the mockup screenshot was not added.

**NEW:**
**Description:**
The test case verifies that the "Оживити картинку" button is clickable upon the availability of the AR item (on the desktop).

**Preconditions:**
Go to the "StreetCode" page.

**Steps to reproduce:**
1. Click on the "Оживити картинку" button.
2. Verify that the page will scroll to the AR item.

**Expected result:**
The page automatically scrolls to the section "AR-історія в Інсті!" and the user can see the QR code.

**Comment by AlbinaVorobiova** [comment]
**UPDATE:**
The corresponding Epic and User story were added to this test case:
User story:https://github.com/ita-social-projects/StreetCode/issues/20
Epic: https://github.com/ita-social-projects/StreetCode/issues/19

**Comment by AlbinaVorobiova** [comment]
The 'Оживити картинку' button is removed (according to the Customer`s requirement).
