### ISSUE TITLE
Improvement [Admin/Interesting facts block]  Admin can change the order of WOW facts after they are created

### ISSUE THREAD

**Issue by DariaAntonenko** [ita-social-projects/StreetCode#389]
**Environment:** OS, Windows 11 
**Browser**: Google Chrome Version 114.0.5735.135
**Reproducible:** always
**Build found:** 1b79c16

**Preconditions**
1. Go to http://185.230.138.173/admin-panel
2. Login as  Admin
3. A WOW facts are added

**Steps to reproduce**
1. Go to the Interesting facts block - WOW - факти
2. Verify if Admin can change the order of WOW facts 

**Actual result**
Admin cannot change the order of WOW facts after they are created 

**Expected result**
Admin can reorder WOW facts after they are created 

**User story and test case links**
E.g.: "User story #123 

[Test case] #361 

https://github.com/ita-social-projects/StreetCode/assets/109734235/bca47e7b-322a-44b8-a069-213a7e3ad755

**Labels to be added**
"Bug", Priority (" hight"), Severity ("medium"), Type ("Functional")

**Comment by SophiaMRI** [comment]
Duplicate - Actual Bag report -> #865
