### ISSUE TITLE
Chronology block

### ISSUE THREAD

**Issue by vladnvp** [ita-social-projects/StreetCode#39]
**As a user I would like to see related to a StreetCode events in a timeline so I will know when an important event happened**

**Description**
This block will allow the user to see all related events as a timeline with the ability to move back and forward and read more about a specific event.

### Acceptance Criteria
1. Title "Хронологія подій" is displayed
2. A red timeline is displayed and a grey square is visible under each year in a timeline.
3. Square under the selected year is bigger than others.
4. Click on another square leads to scroll of a camera film to another event in the selected timeline.
![image](https://user-images.githubusercontent.com/112704799/209579919-84ee5c4a-8f2f-4137-a94f-08532e0395d6.png)
5. Each event is located separately as an element of a camera film. 
6. Each event contains of: a period of time (date, season), Title, Main Text.
7. ~~If all text don't fit in a camera film - "Читати быльше" button should be available and click on it opens a modal window with a full text~~
![image](https://user-images.githubusercontent.com/112704799/209580189-2dc490f4-fe81-4cce-b7d4-95b9c6a7de90.png)
8. Events are displayed from oldest to newest, from left to right
9. Camera film reacts to a scroll and moves accordingly
Scroll down moves camera film to the newest events ->
Scroll up moves camera film ti the oldest events <-
10. Сlicking on previous/next event - moves events cards and locates clicked one to the center
11. The central event has a white outline

When ordering events:
- the beginning of the year is considered as the 1st of January
- the beginning of the season is considered as the first day of its first month,
- the beginning of the month is considered as the first day of this month

Date formats:
<html>
<body>
<b style="font-weight:normal;" id="docs-internal-guid-dac0009b-7fff-b7fc-2554-cc99fe2c4fb8"><div dir="ltr" style="margin-left:0pt;" align="left">

Вид події | Приклад
-- | --
Рік | 1891
Сезон | 1902, осінь
Місяць | 1880, серпень
Дата | 1906, серпень, 2

</div></b>
</body>
</html>

**Epic link**
[(Epic) StreetCode page](https://github.com/ita-social-projects/StreetCode/issues/19)

**Comment by vladnvp** [comment]
UPD to acceptance criteria
9. No more than 400 symbols (including spaces) on each card

Images for the background will be a set of 3 default images

**Comment by vladnvp** [comment]
UPD to acceptance criteria
(NEW)
9. Camera film reacts to a scroll and moves accordingly
Scroll down moves camera film to the newest events ->
Scroll up moves camera film ti the oldest events <-
10. Сlicking on previous/next event - moves events cards and locates clicked one to the center
11. The central event has a white outline

**Comment by vladnvp** [comment]
UPD
1. Title "Хронологія подій" is displayed, **no more than 26 symbols including spaces.**

**Comment by AlbinaVorobiova** [comment]
**NEW item:**
12. The layout of the StreetCode page must be adaptive: desktop (1920px, 1600px, 1025px), tablet (768px), mobile (360px).
