### ISSUE TITLE
Related events and personas block

### ISSUE THREAD

**Issue by vladnvp** [ita-social-projects/StreetCode#40]
**As a user I want to see related to a StreetCode personas/events so I will know about other events/personas**

**Description**
This block will allow the user to find out which personas/events are connected to opened StreetCode and will allow navigating to new pages.

### Acceptance Criteria

1. Title "Зв'язки історії" is displayed
2. Separate card is displayed for each related persona/event.
3. Black and white image is used for a card
4. Hovering over a card of persona/event shows tags that are applicable to current and related StreedCode.
![image](https://user-images.githubusercontent.com/112704799/210262818-7e661b74-0105-4e2c-9e68-643b37c43c3e.png)
5. Click on a card redirects user to the selected StreetCode
6. If there are more than 4 cards - a navigation arrow appears and they allow user to scroll cards + "Дивитися всіх" button appears and clicking on it opens a modal window with a full list of related personas/events
![image](https://user-images.githubusercontent.com/112704799/210259089-2df43ebd-ae6f-43b5-9f9d-ac599ed54c6b.png)
7. Navigation arrows are always aligned to the center to the size of not extended card.
8. Cards are aligned to the left side

**Epic link**
[(Epic) StreetCode page](https://github.com/ita-social-projects/StreetCode/issues/19)

**Comment by vladnvp** [comment]
UPD to acceptance criteria
(NEW)
7. Navigation arrows are always aligned to the center to the size of not extended card.
8. Cards are aligned to the left side

**Comment by vladnvp** [comment]
UPD to acceptance criteria
(NEW) 9. Modal window should have a lool of a provided a design
![image](https://user-images.githubusercontent.com/112704799/214009810-abfe1cfb-84b2-484e-a0b0-84ea9be39ecd.png)

**Comment by vladnvp** [comment]
UPD
NEW - 10. Short description contains no more than 30 symbols including spaces

**Comment by AlbinaVorobiova** [comment]
**NEW item:**
11. The layout of the StreetCode page must be adaptive: desktop (1920px, 1600px, 1025px), tablet (768px), mobile (360px).

**Comment by YuliiaAndreieva** [comment]
UPD: 
If an item in the modal window has common tags, they should be displayed when the pointer moves over the image and become fixed after two seconds, allowing interaction with the common tags.
![update2](https://github.com/user-attachments/assets/4ab5b49c-0fe1-4275-873f-2ae7a9b58431)
