### ISSUE TITLE
[Admin/Chronology block] Created contexts in the list are duplicated.

### ISSUE THREAD

**Issue by SophiaMRI** [ita-social-projects/StreetCode#400]
**Environment:** Windows 11,
Google Chrome Version 111.0.5563.147 (64-bit)
**Reproducible:** Always
**Build found:** Commit 1b79c16

**Type:** Functional
**Priority:** High
**Severity:** Critical

**Preconditions**

1. The "StreetCode page" is opened.

2. Logged as admin.

**Steps to reproduce**

1. Scroll down to the "Chronology" block.

2. Сlick on the '+' button.

3. Сlick on the context field.

4. Select some context from the list.

**Actual result**
Highlights two duplicated context names from the list.

**Expected result**
Highlights only one selected context name from the list.

**User story and test case links**
User story #124 
Test case #398 

https://github.com/ita-social-projects/StreetCode/assets/135108144/21b29573-233c-4b12-974a-5e70a0df4d06

**Comment by KateYatsiuk** [comment]
It's not a bug anymore, we just need to clean the DB and the problem will disappear
