### ISSUE TITLE
Sources block

### ISSUE THREAD

**Issue by vladnvp** [ita-social-projects/StreetCode#41]
**As a user I want to see sources of information which was used on a StreetCode page so I will know where did this information come from**

**Description**
This block will allow the user to review the attached sources of information used for specific StreetCode. This will allow the user to know the place of origin of information, as well this will allow the user to understand which books/articles.. can be used to get more information about StreetCode 

### Acceptance Criteria

1. Title "Джерела" is displayed.
![image](https://user-images.githubusercontent.com/112704799/209583786-5ba3a691-bba6-4621-9355-d1b201c6cb53.png)
2. Separate card for each type of source is displayed.
3. Click on the source card opens a modal window with a list of used sources. (sources can be clickable or not clickable).
~~4. If there are more than 3 cards - a navigation arrow appears and allows the user to scroll cards + "Дивитися всі" button appears and clicking on it opens a modal window with a full list of sources' categories.~~
5. In opened modal window subcategories should be written in **bold**
![image](https://user-images.githubusercontent.com/112704799/211657496-27f45279-aa9c-442d-a769-a54e3ecf0218.png)

![image](https://user-images.githubusercontent.com/112704799/209583798-80efe7da-37f0-4ac6-8ac9-b593b759000f.png)

**Epic link**
[(Epic) StreetCode page](https://github.com/ita-social-projects/StreetCode/issues/19)

**Comment by vladnvp** [comment]
UPD to acceptance criteria
1. Title "Джерела" was changed to "Для фанатів"
![image](https://user-images.githubusercontent.com/112704799/210260900-2bd37832-c88e-4057-9cab-dc444107ef25.png)

**Comment by vladnvp** [comment]
UPD to acceptance criteria
~~4. If there are more than 3 cards - a navigation arrow appears and allows the user to scroll cards + "Дивитися всі" button appears and clicking on it opens a modal window with a full list of sources' categories.~~
button is not expected in this block
(NEW)
5. In opened modal window subcategories should be written in **bold**
![image](https://user-images.githubusercontent.com/112704799/211657496-27f45279-aa9c-442d-a769-a54e3ecf0218.png)

**Comment by AlbinaVorobiova** [comment]
NEW item:
7. The layout of the StreetCode page must be adaptive: desktop (1920px, 1600px, 1025px), tablet (768px), mobile (360px).
