### ISSUE TITLE
[Main StreetCode block]  the text of tags in a modal window is  not well readable

### ISSUE THREAD

**Issue by DariaAntonenko** [ita-social-projects/StreetCode#419]
**Environment:** OS, Windows 11
**Browser**: Google Chrome Version 114.0.5735.135
**Reproducible:** always
**Build found:** https://github.com/ita-social-projects/StreetCode/commit/1b79c162699aafffaa1f620fb97e9eb04fd6e0fb

**Preconditions**
1.Go to the “StreetCode” page

**Steps to reproduce**
1. Find the part with tags under the "Years of life / Date or period" of the event
2. Click on one of the tags
3. A modal window with all StreetCodes with this tag is opened 
4. Verify if the text  of tags in modal window is well visualized and readable

**Actual result**
The text  of tags in modal window is  not well readable: part of the text is cut off, although there is space in the field

**Expected result**
The text  of tags in modal window is well visualized and readable

**User story and test case links**
E.g.: "User story #20 
[Test case] #71 

**Labels to be added**
"Bug", Priority ("low "), Severity ("low"), Type ("UI")

https://github.com/ita-social-projects/StreetCode/assets/109734235/166f6bc5-bf0d-4527-88a5-1749a21acefb

**Comment by AndriiS1** [comment]
It is normal that in slider part of tag can be cut off. And dev team consider that we will not change space between tags.
