### ISSUE TITLE
[Admin/Sources block] The system doesn't display a counter set at 100 symbols.

### ISSUE THREAD

**Issue by SophiaMRI** [ita-social-projects/StreetCode#430]
**Environment:** Windows 11,
Google Chrome Version 122.0.6261.112  (64-bit)
**Reproducible:** Always
**Build found:** Commit [aafbfbc](https://github.com/ita-social-projects/StreetCode/commit/aafbfbc286e9c0ae2ce12bbf8a259104b8edc3ac)

**Type:** UI
**Priority:** Low
**Severity:** Low

**Preconditions**

1. The "StreetCode page" is opened.

2. Logged as admin.

**Steps to reproduce**

1. Scroll down to the "Для фанатів" block.

2. Сlick on the '+' button.

3. Click on the "Категорія" field and 'Add a new category' in the first modal window.
4. Enter the text (e.g. "Подєбрадський полк" Армії УНР) in the field 'Назва" in the second modal window .

**Actual result**
The system allows adding only 23 symbols and displays a counter set at 23 symbols.
![Screenshot_3](https://github.com/ita-social-projects/StreetCode/assets/144954641/09d09c0e-27fc-4f9c-bec2-42673c12f4de)

**Expected result**
The system should allow the entering of 100 symbols and display a counter set at 100 symbols.

**User story and test case links**
User story #125 
Test case #426

**Comment by ruslana-feygina** [comment]
Bug is invalid because there is a user story #833 with new requirement, where the system allows adding only 23 symbols in the field 'Назва".
