### ISSUE TITLE
[Admin/Text and Video block] An error is thrown when previewing the  main text

### ISSUE THREAD

**Issue by DariaAntonenko** [ita-social-projects/StreetCode#478]
**Environment:** OS, Windows 11
**Browser**: Google Chrome Version 114.0.5735.135
**Reproducible:** always
**Build found:** https://github.com/ita-social-projects/StreetCode/commit/d494c372c230bf30fef322fdb50405a1c708c55b

**Preconditions**
1.Go to http://185.230.138.173/admin-panel
2.Login as Admin
3.Go to 'Стріткоди'

**Steps to reproduce**
1.Click on 'Новий стріткод' button
2.Go to the Text and Video block
3.Enter the text ( with e.g 9772 symbols / 1336 words) in the field 'Основний текст'
4.Click on 'Попередній перегляд тексту' button

**Actual result**
The word 'undefined' is highlighted below from the button 'Попередній перегляд тексту'

**Expected result**
The user can view the text as it will look on the site

**User story and test case links**
E.g.: "User story #122 
test case #489 

**Labels to be added**
"Bug", Priority ("hight "), Severity ("hight:"), Type ( "Functional")

https://github.com/ita-social-projects/StreetCode/assets/109734235/7eaf8da9-e7db-4121-bcf0-fe330b8ae312

**Comment by Tysyatsky** [comment]
Tested with 1000+ words.
![image](https://github.com/ita-social-projects/StreetCode/assets/77460353/938afdbc-a263-491d-b9c5-2a5b8adf2b89)

**Comment by DariaAntonenko** [comment]
after clicking on 'Попередній перегляд тексту' button - again the 'undefined' appears and then the text is loaded. it's better to write 'Text is loading

Uploading Стріткод _ Історія на кожному кроці - Google Chrome 2023-08-07 14-45-23.mp4…

' or add a gif
