### ISSUE TITLE
[Main Page] [Desktop] Buttons "До стріткодів" and "Задонатити" are not clickable on the upper and lower sections

### ISSUE THREAD

**Issue by kikimou** [ita-social-projects/StreetCode#572]
**Environment:** Windows 11, Chrome 115.0.5790.171 (Official Build) (64-bit)
**Reproducible:** Always 
**Build found:** [fcc4320](https://github.com/ita-social-projects/StreetCode/commit/fcc432057148d97e6f89447a874adea44ba5fa00)

**Priority:** High
**Severity:** Minor
**Type:** Functional

**Preconditions**
[Main StreetCode page](http://185.230.138.173/) is opened in desktop version of the site

**Steps to reproduce**
1. Scroll down to button "До стріткодів" or "Задонатити"
2. Click on upper or lower side of the button

**Actual result**:
Buttons don't react to clicks

**Expected result**
Redirect to "[Стріткоди](http://185.230.138.173/catalog)" page for "До стріткодів" button
Redirect to "[Донати](http://185.230.138.173/support-us)" page for "Задонатити" button

**User story and test case links:**
Test case #611

**Comment by DariaAntonenko** [comment]
The button "Оживити картинку" is not clickable in the corners.  Only when user clicks on the text Оживити картинку inside the button - the button begin clickable.  The button should be clickable and react everywhere and Redirect to: 
On Desktop should move user to the bottom of the page to block "AR Instagram"
On Mobile should move user to Instagram app with this effect
