### ISSUE TITLE
[StreetCode page] Buttons in progress bar aren't clickable on corners

### ISSUE THREAD

**Issue by kikimou** [ita-social-projects/StreetCode#603]
**Environment:** Windows 11, Chrome 115.0.5790.171 (Official Build) (64-bit)
**Reproducible:** Always
**Build found:** [fcc4320](https://github.com/ita-social-projects/StreetCode/commit/fcc432057148d97e6f89447a874adea44ba5fa00)

**Priority:** Low
**Severity:** Trivial
**Type:** Functional

**Preconditions:** 
1. Ensure your resolution is higher or equal to 1449px of width
2. Go to any streetcode page (e. g. [Юрій Дадак (Руф)](http://185.230.138.173/yuriy-ruf))

**Steps to reproduce**
1. Open progress bar (left lower corner)
2. Try to click on button's corners of progress bar

**Expected result**
Auto scroll to selected part of the page

**Actual result**
Nothing happens

![Image](https://user-images.githubusercontent.com/83531484/259992760-2c007130-c071-42ad-8c03-7e933d60cff0.png)

**User story and test case links:**
Test Case #685

**Comment by AndriiS1** [comment]
Pull request here: https://github.com/ita-social-projects/StreetCode_Client/pull/632
