### ISSUE TITLE
[StreetCode page] Borders of the page start eating the borders of streetcode card when resolution is from 381 to 360px

### ISSUE THREAD

**Issue by kikimou** [ita-social-projects/StreetCode#606]
**Environment:** Windows 11, Chrome 115.0.5790.171 (Official Build) (64-bit)
**Reproducible:** Always
**Build found:** [fcc4320](https://github.com/ita-social-projects/StreetCode/commit/fcc432057148d97e6f89447a874adea44ba5fa00)

**Priority:** Low
**Severity:** Minor
**Type:** UI

**Preconditions**
Go to any streetcode page (e. g. [Роман Ратушний (Сенека)](http://185.230.138.173/roman-ratushnyi))

**Steps to reproduce**
1. Open ChromeDevTools (F12)
2. Enter mobile mode (Ctrl + Shift + M)
3. Choose "Responsive" dimensions (header of ChromeDevTools)
4. Set resolution to 381px of width with 100% zoom ([visual example](https://i.ibb.co/XXxFkYt/image.png))
5. Reduce resolution by 1px to 360px of width

**Expected result**
The borders of the card perfectly stick with the borders of the site (as [in mockup](https://www.figma.com/file/9ydz23Y1yKPGx92lsqBhak/StreetCode?type=design&node-id=3555-8878&mode=design&t=0K01n4zsNOEM0uq7-4))
![Image](https://user-images.githubusercontent.com/83531484/260031583-4757238c-c5f8-449f-a10d-e34b07ee1c39.png)

**Actual result**
The borders of the page start eating the borders of a card when the resolution is from 381 to 360px of width

(colors reversed on the screenshot to show borders better)
![Image](https://user-images.githubusercontent.com/83531484/260032861-acf81f46-7804-4f14-917c-90463a91a7b0.png)

**User story and test case links:**
#614

**Comment by iskoryk** [comment]
The borders of the page start eating the borders of a card when the resolution is less 381px of width
