### ISSUE TITLE
[Admin/Авторство] Improvement: remove panel text alignment

### ISSUE THREAD

**Issue by DariaAntonenko** [ita-social-projects/StreetCode#633]
**Environment:** OS, Windows 11
**Browser**: Google Chrome Version 114.0.5735.135
**Reproducible:** always
**Build found:**  https://github.com/ita-social-projects/StreetCode/commit/dd96607bb61a4d58042621da2ce598c0de947390

**Preconditions**
1. Go to the site as admin.

**Steps to reproduce**
1. Click on 'Новий стріткод'
2. Scroll down to the field  'Авторство'
4. According the mock-up Authorship text should always be on the right side: https://www.figma.com/file/9ydz23Y1yKPGx92lsqBhak/StreetCode?type=design&node-id=5827-11482&mode=design&t=Ay4DCXPpC7ZtCs43-4
5. Pay attention to the panel text alignment

**Actual result**
This panel allows you to put text in different directions from the admin side 

**Expected result**
The admin does not need this panel, since the text in any case should be on the right side according to the mockup

**Labels to be added**
"Bug", Priority ("pri: low "), Severity ("severity:low"), Type ("Functional")
![avtorstvo](https://github.com/ita-social-projects/StreetCode/assets/109734235/ef994c0e-0b06-4309-a941-85065457c330)

**Comment by KateYatsiuk** [comment]
This issue is closed due to the replacement of the TinyMCE editor with a new one - ReactQuill.
