### ISSUE TITLE
[Streedcode page] During loading white spaces are present on corners on different resolutions

### ISSUE THREAD

**Issue by kikimou** [ita-social-projects/StreetCode#634]
**Environment:** Windows 11, Chrome 115.0.5790.171 (Official Build) (64-bit)
**Reproducible:** Always
**Build found:** [7853445](https://github.com/ita-social-projects/StreetCode/commit/7853445cc1887c46a7b325f7e3430cc2cb8cda31)

**Priority:** Low
**Severity:** Trivial
**Type:** UI

**Preconditions:**
Set resolution to 1920x1080px or 1600x1200px

**Steps to reproduce:**
1. Go to any StreetCode page (e.g. http://185.230.138.173/roman-ratushnyi)
2. Reload the page
3. Pay attention to the right, upper, and lower areas during loading

**Actual result:**
1. White space on the right side of the screen with a resolution of 1920x1080 ([screenshot](https://i.ibb.co/6Dp6qK5/image.png))
2. White spaces on the upper and lower sides of the screen with a resolution of 1600x1200 ([screenshot](https://i.ibb.co/3vYCTSt/image.png))

**Expected result:**
No white spaces (as in [mockup](https://drive.google.com/file/d/1sgYOh-LqXgCROawmAiXRjEz1oLH-vz1P/view?usp=drive_link))

**Epic:** https://github.com/ita-social-projects/StreetCode/issues/19
**Test Cases:** #1270, #614

**Comment by SophiaMRI** [comment]
On a 1920x1080 resolution screen, there is still a white line on the right side upon reboot.

**Comment by AlbinaVorobiova** [comment]
There are no white spaces on the upper and lower sides of the screen with a resolution of 1600x1200px.

**Comment by AlbinaVorobiova** [comment]
There is a white space on the right side of the screen with a resolution of 1920px, 1600px, and 1025px.
