### ISSUE TITLE
[Test case] [Main StreetCode block] Verify if the user can see concise information at the top of the page about a person or event

### ISSUE THREAD

**Issue by SvitlanaOleksiv** [ita-social-projects/StreetCode#64]
**Priority: high**

**Description:**
Test case verifies if the user can see concise information at the top of the page about a person or event

**Preconditions**
1. Go to  “StreetCode” page

**Steps to reproduce**
1. Verify if the following sections are present (according to the mockup)

- Background image is applied for this block on a page
- Animated image is displayed and is starts automatically and stops after 1 playback
- Verify if the user is able to switch to another image using squares (black/white image and colored)
- Verify if the user is able to switch to another image after clicking on the side of the picture
- Verify if the dimensions are proportional to the fields of the picture - 190x165
- "Стріткоди" + Full StreetCode name is displayed

![image](https://user-images.githubusercontent.com/110596345/211349047-4182bfb6-c39b-4bde-a512-0518fc9b6511.png)

- "Streetcode number" is displayed
- "Name of a person or event" is displayed
- "Years of life / Date or period" of the event

![image](https://user-images.githubusercontent.com/110596345/211349898-93a22bfa-219a-40ca-9389-0327e9b59b20.png)

2. Verify if the "Tags are displayed" and clickable (tags with keywords)
3. Verify if the "Teaser" is displayed (No more than 400 symbols including spaces if there is 1 paragraph
OR No more than 400 symbols including spaces if there are 2 paragraphs)
4. Verify if the "Прослухати текст" button is displayed 
5. Verify if the "Оживити картинку" button is displayed
6. Verify if the after clicking "Оживити картинку" button  the user automatically goes to the end of the page to the section "Грай з AR в Instagram"
7. Verify if the"Donate button" button is displayed and pinned to the bottom right corner of the screen

**Expected result**
The following sections are displayed according to the mockup.

![mock up StreetCode](https://user-images.githubusercontent.com/110596345/211352273-d893d887-999a-4608-aea7-d2e9cffadac3.png)

**User story: https://github.com/ita-social-projects/StreetCode/issues/20**

**Epic: https://github.com/ita-social-projects/StreetCode/issues/19**

**Comment by AlbinaVorobiova** [comment]
**UPDATE to "Description":**
Test case verifies if the user can see concise information at the top of the page about a person or event

**NEW "Description":**
The test case verifies that the user can see concise information about a person or event at the top of the StreetCode page: pictures, tags, teaser, and other block elements (according to the Mockup).

**Comment by AlbinaVorobiova** [comment]
**UPDATE to "Steps to reproduce":**
1. Verify if the following sections are present (according to the mockup)
- Background image is applied for this block on a page
-  Animated image is displayed 
- Verify if the dimensions are proportional to the fields of the picture - 190x165
- "Стріткоди" + Full StreetCode name is displayed
- "Streetcode number" is displayed
- "Name of a person or event" is displayed
- "Years of life / Date or period" of the event
2. Verify if the "Tags are displayed" and clickable (tags with keywords)
3. Verify if the "Teaser" is displayed (No more than 520 symbols including spaces if there is 1 paragraph
OR No more than 455 symbols including spaces if there are 2 paragraphs)
4. Verify if the "Прослухати текст" button is displayed 
5. Verify if the "Оживити картинку" button is displayed upon the availability of the AR item
6. Verify if the"Donate button" button is displayed and pinned to the bottom right corner of the screen 

**What was wrong?**
1. There are different mistakes in English words.  
2. No need to duplicate the "displayed "word many times.
3. Wrong dimensions of the animated picture.
4. The items can be more structured.
5. Some information about the required UI elements is not available here.

**NEW "Steps to reproduce":**
1. Verify that the following sections are displayed:
▪️ Background image
▪️ Animated colored image and it can be switched to the white-black picture using squares 
▪️ "Стріткоди" + Full StreetCode name
▪️ "Streetcode number"
▪️ "Name of a person or event"
▪️ "Years of life / Date or period" of a person or event
▪️ "Tags"
2. Verify that the animated picture`s dimensions are proportional to its fields: 415х542 px
3. Verify that the "Teaser" is displayed and its length is:
▪️ No more than 520 symbols including spaces if there is 1 paragraph
OR 
▪️ No more than 455 symbols including spaces if there are 2 paragraphs
4. Verify that the "Прослухати текст" button is displayed upon the availability of the audio record.
5. Verify that the "Аудіо на підході" button is displayed in the absence of the audio record.
6. Verify that the "Оживити картинку" button is displayed upon the availability of the AR item (only on Desktop).
7. Verify that the "Задонатити" button is displayed and pinned to the bottom right corner of the screen.

**Comment by AlbinaVorobiova** [comment]
**UPDATE to "Expected result":**
The old mockup was added here.
![старый мокап](https://github.com/ita-social-projects/StreetCode/assets/160258291/6ff3669e-635c-433d-9381-205d9b9c5ca4)

**NEW "Expected result":**
The new mockup is added.

**Comment by AlbinaVorobiova** [comment]
The "Оживити картинку" button is displayed on the Mockup but, according to the Customer`s requirement, this button was removed from the mockup and stage version.

**Comment by AlbinaVorobiova** [comment]
**NEW items for verifying:**
7. Verify that elements do not interact with each other during window resize.
8. Verify that elements do not interact with each other for 125% and 150% screen scale.
9. Verify that the colors of the elements are corresponded to the mockup. 
10. Verify that the fonts are corresponded to the mockup.
