### ISSUE TITLE
[Streetcode page] Text goes beyond the limit of the chronology card

### ISSUE THREAD

**Issue by kikimou** [ita-social-projects/StreetCode#648]
**Environment:** Windows 11, Chrome 115.0.5790.171 (Official Build) (64-bit)
**Reproducible:** Always
**Build found:** [a004670](https://github.com/ita-social-projects/StreetCode/commit/a0046702b7f8189d0bdc921662e67806cdf3d95f)

**Priority:** Low
**Severity:** Minor
**Type:** UI

**Preconditions:**
1. [Роман Ратушний (Сенека) page](http://20.120.82.146/roman-ratushnyi) is opened
2. Resolution is in 360-1024px

**Steps to reproduce:**
1. Scroll to the chronology block
2. Switch to "Домашній арешт" card

**Actual result:**
Text goes beyond the limits of the chronology card [(screenshot)](https://i.ibb.co/BPmPMNY/image.png)

**Expected result:**
Text in the limit of the chronology card [(as on the mockup)](https://www.figma.com/file/9ydz23Y1yKPGx92lsqBhak/StreetCode?type=design&node-id=4069-8206&mode=design&t=OiqSbpfOBK6TJnxX-4)

**User story and test case links:**
#614

**Comment by SophiaMRI** [comment]
Duplicate - Actual Bag report -> #861
