### ISSUE TITLE
[Popup/Modal windows] During quick clicking on empty area or close button the window opens and closes

### ISSUE THREAD

**Issue by kikimou** [ita-social-projects/StreetCode#658]
**Environment:** Windows 11, Chrome 116.0.5845.111 (Official Build) (64-bit)
**Reproducible:** Always
**Build found:** [a004670](https://github.com/ita-social-projects/StreetCode/commit/a0046702b7f8189d0bdc921662e67806cdf3d95f)

**Priority:** Low
**Severity:** Minor
**Type:** Functional

**Steps to reproduce:**
1. Open any popup window (e.g. "Долучитися" on the main page)
2. Non-stop click on the empty area or close button

**Actual result:**
The window opens/closes until you stop clicking

https://github.com/ita-social-projects/StreetCode/assets/83531484/102b7541-4ccb-4635-bd68-b334f027a1ad

**Expected result:**
The window closes after 1st click

TC #653

**Comment by SophiaMRI** [comment]
Duplicate - Actual Bag report -> #818
