### ISSUE TITLE
[Admin/Sources block] When creating a new category, this category does not immediately appear in the list. After creating the second category, the first created category becomes inactive

### ISSUE THREAD

**Issue by DariaAntonenko** [ita-social-projects/StreetCode#708]
**Environment:** Environment: OS: Windows 10 Pro
**Browser**: Google Chrome Version 111.0.5563.112.
**Reproducible:**   sometimes 
**Build found:** https://github.com/ita-social-projects/StreetCode/commit/32678279edc93adddccdce4d4e6774d86415674c

**Preconditions**
1. Go to the site as admin.

**Steps to reproduce**
1. Go to creating the new Streetcode
2. Scroll down to the Source block
3. Click in Add ( +) button 
4. In the field 'Категорія' create a new category ( e.g new category)
5. In the field 'Категорія' select the created category from the category list
6. In the field 'Категорія' create a new category ( e.g новая категория)

**Actual result**
The created category does not immediately appear in the list of categories, but only after some time of scrolling through the entire list of categories.
After creating the second category, the first created category becomes inactive

**Expected result**
The created category  immediately appears in the list of categories and admin can choose it.
After creating the second category, the first created category becomes active

**User story and test case links**
E.g.: "User story #125 

https://github.com/ita-social-projects/StreetCode/assets/109734235/e516f099-8d62-4d20-b012-a0b70dd2998b

![Screenshot_1](https://github.com/ita-social-projects/StreetCode/assets/109734235/8ddf4017-b6ff-4126-bc1c-0fce1464d7eb)

**Labels to be added**
"Bug", Priority ("pri:hight "), Severity ("severity:hight"), Type ("Functional")

**Comment by KateYatsiuk** [comment]
Please, retest it, a new version has been released on the stage recently. I cannot reproduce it locally
