### ISSUE TITLE
[Test case] [Main StreetCode block] Verify that "Tags" are displayed on the Main StreetCode block and clicking on any tag opens a modal window.

### ISSUE THREAD

**Issue by SvitlanaOleksiv** [ita-social-projects/StreetCode#71]
**Priority: high**

**Description:**
Test case verifies if clicking on the tag opens a modal window with all StreetCodes with this tag.

**Preconditions:**
1. The "StreetCode" page is opened.

**Steps to reproduce:**
1. Find the tags under the "Years of life / Date or period" of the event.

![image](https://user-images.githubusercontent.com/110596345/211510914-6c056f24-c8ce-4057-9d5e-9ec1d3b31bec.png)

2. Сlick on one of the tags.
3. Verify that after hovering over the tag, it changes in shade (becomes darker).
4. Verify that clicking on the tag opens a modal window with all StreetCodes relevant to this tag.
5. Verify that the modal window`s text is displayed and readable.

**Expected result:**
 Clicking on the tag opens a modal window with all StreetCodes relevant to this tag.

**User story: https://github.com/ita-social-projects/StreetCode/issues/20**

**Epic: https://github.com/ita-social-projects/StreetCode/issues/19**

**Comment by AlbinaVorobiova** [comment]
UPDATE to the test case`s title:

**Comment by AlbinaVorobiova** [comment]
**UPDATE to "Steps to reproduce":**
1. Find the part with tags under the "Years of life / Date or period" of the event
image
3. Сlick on one of the tags
4. Verify if the after hovering over the tag, it changes in shade (becomes darker)
5. Verify if the clicking on the tag opens a modal window with all StreetCodes with this tag
6. Verify if the text in modal window is well visualized and readable

**What was wrong?**
1. The 3 item follows after the 1 item. 
2. The 4-6 items should be written correctly in English.

**NEW "Steps to reproduce":**
1. Find the tags under the "Years of life / Date or period" of the event.
2. Сlick on one of the tags.
3. Verify that after hovering over the tag, it changes in shade (becomes darker).
4. Verify that clicking on the tag opens a modal window with all StreetCodes relevant to this tag.
5. Verify that the modal window`s text is displayed and readable.
