### ISSUE TITLE
[Admin/Text block and Authorship ] When admin click on edit Streetcode, the text and authorship fields disappear

### ISSUE THREAD

**Issue by DariaAntonenko** [ita-social-projects/StreetCode#716]
**Environment:** Environment: OS: Windows 10 Pro
**Browser**: Google Chrome Version 111.0.5563.112.
**Reproducible:** always
**Build found:** https://github.com/ita-social-projects/StreetCode/commit/b5076960946904b924bd472ec298094c54cc15e6

**Preconditions**
1. Go to the site as admin.
2. Streetcode is created ( text field  and Authorship are filled )

**Steps to reproduce**
1. Go to eaditing the created Streetcode
2. Scroll down to the Text block and Authorship

**Actual result**
These fields do not display information that was previously entered when creating the Streetcode.

**Expected result**
These fields display information that was previously entered when creating the street code.

**User story and test case links**
E.g.: "User story #122 

https://github.com/ita-social-projects/StreetCode/assets/109734235/937845d8-98db-4937-8b15-fb0d801c2f50

**Comment by Adeodonne** [comment]
Duplicate
https://github.com/ita-social-projects/StreetCode/issues/710
