### ISSUE TITLE
History map - part 1

### ISSUE THREAD

**Issue by vladnvp** [ita-social-projects/StreetCode#76]
**Description**
This block will allow the user to see all existing toponyms for a StreetCode.

### Acceptance Criteria
1. Title "Мапа історії" is displayed
2. Map layers switcher is displayed with following options:
- Вулиці
- Стріткоди
- Маршрути (маршрути will be available in next releases)
3. Background image is displayed
4. Map has indicated in Figma design
**"Вулиці" layer**
3.1. Information with a number of specific objects named as a Street Code is displayed
3.2. Circles should be near the cities/regions where objects are available
3.3. Hover over the circle should open a modal window (but maybe pop-over?) with what?
**"Стріткоди" layer**
5.1. Not specified by the customer

![image](https://user-images.githubusercontent.com/112704799/211923953-08132095-f95b-45e7-b49d-5c6cb13aa9fc.png)

Data source for toponyms - https://index.ukrposhta.ua/postcodes-and-offices

**Epic link**
https://github.com/ita-social-projects/StreetCode/issues/19

**Comment by vladnvp** [comment]
To be clarified
1. We will not get data from UkrPoshta about parks and square
2. Can we connect to this data in live? this is an CSV file in ZIP?
3. Can we locate squares on smaller item then Oblast'
4. Подумати, що на цій сторінці показувати при наведенні на позначку в модальному вікні - as for me just this detailed info, bur per hovered circle
![image](https://user-images.githubusercontent.com/112704799/211924989-d6d75d03-0b96-4053-ae11-e0acaefccf49.png)
5. При деталізації мапи “розмножувати” позначки, при укрупненні – збирати до купи відповідно до видимих районів / локацій. - How to zoom?
6. How to count streetcodes? as for now we will not have this data

**Comment by AlbinaVorobiova** [comment]
**NEW item:**
5. The layout of the StreetCode page must be adaptive: desktop (1920px, 1600px, 1025px), tablet (768px), mobile (360px).
