### ISSUE TITLE
[About us] When reloat the page, it switches to the first category "Основний склад"

### ISSUE THREAD

**Issue by DariaAntonenko** [ita-social-projects/StreetCode#773]
**Environment:** all
**Reproducible:** always
**Build found:** https://github.com/ita-social-projects/StreetCode/commit/64cf50fd790e4244e06f6c8c906647301ea70c3d

**Preconditions**
 1.Go to the site as user.

**Steps to reproduce**
1. Click on Main Menu  in the upper right corner of the site
2. Click on  'Про нас'
3. Scroll down to the block 'Команда'
4. Сhoose the category 'Дизайнери та ілюстратори' ( or 'Консультанти', 'IT команда' )
5. Reloat the page

**Actual result**
The page switches to the first category 'Основний склад'

**Expected result**
The page will switch to the last category the user selected (e.g 'Дизайнери та ілюстратори' )

**Labels to be added**
"Bug", Priority ("pri: low"), Severity ("severity: low"), Type ("Functional")

https://github.com/ita-social-projects/StreetCode/assets/109734235/d1d778f8-1edb-4fe5-8054-02ad9965c6ce

**Comment by iskoryk** [comment]
According to customer requirements after reloading the page "Про нас" in the teams' field must be displayed as "Основний склад".

**Comment by iskoryk** [comment]
According to customer requirements after reloading the page "Про нас" in the teams' field must be displayed as "Основний склад".
