### ISSUE TITLE
[Team block][CO#2, 3, 4, 5]The text is cropped and is superimposed on the field of  social links

### ISSUE THREAD

**Issue by DariaAntonenko** [ita-social-projects/StreetCode#794]
**Environment:** OS, Windows 11 . Browser: Google Chrome Version 114.0.5735.135.
   Iphone 11 Pro
**Reproducible:** always,
**Build found:** https://github.com/ita-social-projects/StreetCode/commit/64cf50fd790e4244e06f6c8c906647301ea70c3d

**Preconditions**
 1.Go to the site as [admin](https://stage.streetcode.com.ua/admin-panel/login).

**Steps to reproduce**
1. Go to creating a new team member
2. Tick "Ключовий член команди"
3. Fill in all  fields
4. Fill out the 'Прізвище та ім'я' and 'Опис' fields  with the maximum number of characters
5. Сlick on the button 'Зберегти' 
5. Open the Main page of the site from the user side
6. Scroll down to the 'Team' block
7. Note the team member that was created

**Actual result**
 The text is cropped and is superimposed on the field of  social links ( on desktop version) 
 The text is cropped  ( on mobile version) 

**Expected result**
The text is  not cropped and is not superimposed on the field of  social links ( on desktop version) 
The text is  not cropped  ( on mobile version)

![72e95a8e-b78a-47ad-9412-4318ffdf58e2](https://github.com/ita-social-projects/StreetCode/assets/109734235/66f80652-0434-4d2d-8084-e40334558ed0)
![43e5e71c-b184-46d8-8cfb-9ee76919ae40](https://github.com/ita-social-projects/StreetCode/assets/109734235/be2ddbf9-6765-4960-b2b8-89125e56323c)
![Screenshot_6](https://github.com/ita-social-projects/StreetCode/assets/109734235/7ded61dc-d1a5-4074-b43a-b309c907ac05)

https://github.com/ita-social-projects/StreetCode/assets/109734235/e5eae2c2-6a26-43ef-a4b3-16c023ea5526

**User story and test case links**
E.g.: "User story #695 

**Labels to be added**
"Bug", Priority ("pri: hight"), Severity ("severity:low"), Type ("UI")

**Comment by iskoryk** [comment]
Tablet 768-1024px.
The central enlarged card is cut off.
<img width="519" alt="Screenshot 2024-01-08 at 20 47 10" src="https://github.com/ita-social-projects/StreetCode/assets/130586498/5fe7b5a6-ffa1-4652-a8ec-03c7db0bbc01">
