### ISSUE TITLE
[Wow-факти/News] The button 'Трохи ще' is cut off or disappears  when the title of the wow fact  and the main text has the maximum number of characters and the main text is cut off at the bottom / text is cutt off in the news

### ISSUE THREAD

**Issue by DariaAntonenko** [ita-social-projects/StreetCode#801]
**Environment:** OS, Windows 11 . Browser: Google Chrome Version 114.0.5735.135.
  Iphone 11 Pro
  Galaxy S9
**Reproducible:** always
**Build found:** https://github.com/ita-social-projects/StreetCode/commit/64cf50fd790e4244e06f6c8c906647301ea70c3d

**Preconditions**
1. Go to the site as admin.

**Steps to reproduce**
1. Go to creating The Streetcode
    Fill in all required fields
    Create at least 1 Wow fact: 
fill in the 'Заголовок'and 'Основний текст' fields with the maximum number of characters
    Сlick on the button 'Опублікувати' at the bottom of the page.
    Open the creacted Streetcode from the user side on desktop version
    Scroll down to 'Wow-факти' block and click on 'Трохи ще' button  ( the text is cut off at the bottom and the scroll is overlap  the modal window)
    Open the creacted Streetcode from the user side on mobile and tablet version
    Scroll down to 'Wow-факти' and pay attention on The button 'Трохи ще'

2. Go to creating News
    Fill in all required fields ( in the field 'Заголовок' fill in the maximum number of characters )
    Click on 'Зберегти'  button
    Go to the site as user and pay attention on this news

**Actual result**
1 Desktop version:
The text is cut off at the bottom and the scroll  is overlap  the  modal window
2 News text is cut off

1 Mobile and tablet version:
The button 'Трохи ще' is cut off or disappears  when the title of the wow fact  and the main text has the maximum number of characters

**Expected result**
1 Desktop version:
The text is not cut off at the bottom and the scroll does not overlap  the modal window
2 News text is not cut off

1 Mobile and tablet version:
The button 'Трохи ще' is not cut off or disappears  when the title of the wow fact  and the main text has the maximum number of characters

**Desktop**:

https://github.com/ita-social-projects/StreetCode/assets/109734235/5b333a96-cb81-457b-8cb5-0a41ecbb7aff

![Screenshot_13](https://github.com/ita-social-projects/StreetCode/assets/109734235/819f57c6-4c73-40e9-9473-317696e5a10e)

**Iphone 11 Pro**:

https://github.com/ita-social-projects/StreetCode/assets/109734235/20557448-7be6-4094-bd2c-a03c7286dd65

  **Galaxy S9**:

![photo_5323537802647950930_y](https://github.com/ita-social-projects/StreetCode/assets/109734235/73d345e9-17a7-4f8b-a0f8-9db319c65d3e)
![photo_5323537802647951014_y](https://github.com/ita-social-projects/StreetCode/assets/109734235/e1e28589-56f7-49c4-9322-b853f1a16f3f)
![photo_5323537802647951013_y](https://github.com/ita-social-projects/StreetCode/assets/109734235/567c2f5c-3158-40fa-b786-43d56d22594a)

**Tablet**:
![Screenshot_3](https://github.com/ita-social-projects/StreetCode/assets/109734235/2dbd4736-232d-4f8e-9584-0b0ac7e10648)

**Also make shared component for wow-fact, streetcode-card on main page, news card and job card.**

**User story and test case links**
E.g.: "User story #26 

**Labels to be added**
"Bug", Priority ("pri: hight"), Severity ("severity: low"), Type ("UI, "Functional")

**Comment by iskoryk** [comment]
Mobile. Main page.
If Admin adds the maximum permissible number of characters to the title of the main text, it does not fit into the frame on the main page on mobile.
![2023-11-07 19 55 24](https://github.com/ita-social-projects/StreetCode/assets/130586498/23dcce6e-7974-4559-96a2-6d517608b477)
