### ISSUE TITLE
[Admin/Sources block] [From Customer] Placement of categories which created in English is not in alphabetical order

### ISSUE THREAD

**Issue by DariaAntonenko** [ita-social-projects/StreetCode#815]
**Environment:** OS, Windows 11 .
**Browser**: Google Chrome Version 114.0.5735.135.
**Reproducible:** always
**Build found:** https://github.com/ita-social-projects/StreetCode/commit/77fb021ad16c11d189d744dff099c9920c0873bb

**Preconditions**
1. Go to the site as admin.
2. At least 5 categories have been created in English.

**Steps to reproduce**
1. Go to creating Streetcode or editing
2. Scroll down to 'Sources block' (Для фанатів)
3. Click on Add button
4. Select a category from the list 
5. Pay attention on the placement of categories which created in English 

**Actual result**
Placement of categories which created in English is not in alphabetical order

**Expected result**
Placement of categories which created in English and Ukrainian is in alphabetical order

https://github.com/ita-social-projects/StreetCode/assets/109734235/bfc885c4-76f2-43b0-a30c-641278785113

**User story and test case links**
E.g.: "User story #125 

**Labels to be added**
"Bug", Priority ("pri: low "), Severity ("severity: low"), Type ("Functional")

**Comment by SophiaMRI** [comment]
It doesn't reproduce anymore.
