### ISSUE TITLE
Admin/Job

### ISSUE THREAD

**Issue by anastasiavia** [ita-social-projects/StreetCode#836]
**As an** admin **I want to** add new vacancies and edit existing one **so that** I will be able to help people to find new job.

### Acceptance Criteria
1. Admin is able to create new vacancy using "Додати нову вакансію" button. After that, modal window should be appeared.
2. Admin is able to add title. This is mandatory field. Symbols limit is no more than 50.
3. Admin is able to point status of vacancy using dropdown.
4. Admin is able to add short description for vacancy. He can go back to the previous action or forward (if it has been done), make text bold using "Bold" button, italicize it using "Italic" button and clear the text format using the "Clear" button. This is non-mandatory field.
5. Admin is able to add salary. This is mandatory field. Symbols limit is no more than 15.
6. Admin is able to edit existing vacancy using "pensil" button.
7. Admin is able to delete existing vacancy using "trash bin" button.

**Epic link**
 [Epic(StreetCode)](https://github.com/orgs/ita-social-projects/projects/21/views/1?filterQuery=epic+1&pane=issue&itemId=29554917)

**Comment by BDaria** [comment]
_Updated:_
Item 10 was added.

**Comment by arisssha** [comment]
Edited acceptance criteria and added criterion #11.
