### ISSUE TITLE
[Streetcode page]  The vertical progress bar disappears from 1448 px

### ISSUE THREAD

**Issue by DariaAntonenko** [ita-social-projects/StreetCode#841]
**Environment:** OS, Windows 11 .
**Browser** Google Chrome Version 114.0.5735.135.
**Reproducible:** always
**Build found:** https://github.com/ita-social-projects/StreetCode/commit/77fb021ad16c11d189d744dff099c9920c0873bb

**Preconditions**
1. Go to the site as user.

**Steps to reproduce**
1. Go to 'Streetcode'
2. Click on vertical progress bar 
3. Сheck that the progress bar is present on the desktop version (from 1025 px)

**Actual result**
The vertical progress bar disappears from 1448 px and below

**Expected result**
The vertical progress bar is present on the desktop version ( from 1025 px) 

https://github.com/ita-social-projects/StreetCode/assets/109734235/c97ef5b3-9188-4ca8-87c8-2fc02b874d50

**User story and test case links**
E.g.: "User story #77 

**Labels to be added**
"Bug", Priority ("pri: medium "), Severity ("severity: low"), Type ("Functional")

**Comment by iskoryk** [comment]
The bug is reproduced as well on MacBook Air, Apple M1. 
Brauser: Chrome, Safari. 
Displays 2560x1600.
If you open DevTool and select the same screen size (2560x1600), the progress bar is present, but it is absent on real computers.
