### ISSUE TITLE
[Admin][Авторство/Для фанатів/Вакансії] Text formats do not work correctly

### ISSUE THREAD

**Issue by iskoryk** [ita-social-projects/StreetCode#844]
**Environment:** All
**Reproducible:** always
**Build found:** [d61ab6f](https://github.com/ita-social-projects/StreetCode/commit/d61ab6f1530b63cb2fa12e48ac923e90fccd9de1)

**Priority:** Medium.
**Severity:** Critical.
**Type:** UI.

**Preconditions**
1. Log in as Admin.

**Steps to reproduce**
1. Create a new Streetcode/Вакансія (or edit an existing one).
2. Fill in all mandatory fields and "Заголовок", "Основний текст".

3. Scroll down to fields Авторство/Для фанатів/Вакансії.
3.1. Select all the text in the field "Текст"/"Опис вакансії" and change its format to "Заголовок 1".
3.2. Select all the text in the field "Опис вакансії" and change its format to "Заголовок 2".
3.3. Select all the text in the field "Опис вакансії" and change its format to "Заголовок 3".
3.4. Select all the text in the field "Авторство"/"Для фанатів"/"Вакансії" and change its format to "Форматований".

4. Click Зберегти/Опублікувати.
5. Open this Streetcode/Вакансія and pay attention to the field Авторство/Для фанатів/Вакансії.

**Actual result**
**3.1.1.** [Авторство] Lines of text overlap.
<img width="1214" alt="Screenshot 2023-11-24 at 11 35 54" src="https://github.com/ita-social-projects/StreetCode/assets/130586498/9e706705-ba10-4c01-aa43-581f853a12d1">

3.1.2. [Для фанатів] The text on the Admin page and after publication does not look the same.

https://github.com/ita-social-projects/StreetCode/assets/130586498/22009f78-80af-4cfd-840f-8581c5c116e6

3.1.3. [Вакансії] The card of published Вакансія becomes bigger than on the mockup.

https://github.com/ita-social-projects/StreetCode/assets/130586498/3e1bb81a-baf6-43ce-8c18-c4a864d247f8

**3.2.** Text looks different in the preview of vacancy and full vacancy after clicking "Трохи ще".
<img width="1447" alt="Screenshot 2023-11-24 at 11 27 16" src="https://github.com/ita-social-projects/StreetCode/assets/130586498/e1ccaa3e-0195-4db6-ba15-4319f35f1728">

**3.3.** Text looks different in the preview of vacancy and full vacancy after clicking "Трохи ще".
<img width="1198" alt="Screenshot 2023-11-24 at 11 29 13" src="https://github.com/ita-social-projects/StreetCode/assets/130586498/60c42b47-f57e-40f5-a37d-346e011dff53">

**3.4.** The text is displayed as one-few long line, depending on the amount of text.
3.4.1. [Авторство].
<img width="1345" alt="Screenshot 2023-11-24 at 11 38 51" src="https://github.com/ita-social-projects/StreetCode/assets/130586498/b037b707-6815-4e06-83b8-fe161e9eaeb6">
3.4.2. [Для фанатів].

https://github.com/ita-social-projects/StreetCode/assets/130586498/874787c2-12c0-475e-9d73-e28c9833ca68

3.4.3. [Вакансії].
<img width="1435" alt="Screenshot 2023-11-24 at 11 33 47" src="https://github.com/ita-social-projects/StreetCode/assets/130586498/fbb35031-43b9-4cac-930c-61b86cb6ec86">

**Expected result**
The list of font formats showed options to choose between:  
- Заголовок 4
- Заголовок 5
- Заголовок 6
- Абзаци

**User story:** #122 
**Test case:** #485

**Comment by SophiaMRI** [comment]
Duplicate - Actual Bag report -> #1068
