### ISSUE TITLE
[StreetCode page] [Chronology] The selected square under the year becomes darker and moves

### ISSUE THREAD

**Issue by SophiaMRI** [ita-social-projects/StreetCode#893]
**Environment:** Mobile (Samsung Galaxy S9)
**Reproducible:** Always
**Build found:**  [daea670](https://github.com/ita-social-projects/StreetCode/commit/daea6706cc3699ee07a77d7c61fa69d16f7af348)

**Preconditions**
1. The site is open.
2. At least one StreetCode with a 'Chronology' block has been created.

**Steps to reproduce**
1. Open the StreetCode page.
2. Scroll down to the 'Chronology' block.
3. Click on the grew square.
4. Using the camera film, scroll to either the right or left side.

**Actual result**
The dark square stays in the same place and moves.

https://github.com/ita-social-projects/StreetCode/assets/135108144/4188ea70-bc29-4386-bbf2-fd404ebdaa5e

**Expected result**
The square in the middle is always the same.

[Mockup](https://www.figma.com/file/9ydz23Y1yKPGx92lsqBhak/StreetCode?type=design&node-id=3555-8877&mode=design&t=re6lIqsyZhCNEIS2-4)

**User story and test case links**
User story #39
[Test case] #345

**Comment by Mikhail-Kolpakov** [comment]
Not reproducible.
