### ISSUE TITLE
[Test Case] [UP button] Verify if the UP button will allow the user to return to the top of the page in one click.

### ISSUE THREAD

**Issue by SvitlanaOleksiv** [ita-social-projects/StreetCode#93]
**Priority: high**

Description:
Test case verifies  if the  UP button will allow the user to return to the top of the page in one click.

**Preconditions**
1. Go to “StreetCode” page

**Steps to reproduce**
1. Verify if the button UP appears after 2nd screen (1600 px)
2. Verify if the button UP is displayed on a white background
![Screenshot_15](https://user-images.githubusercontent.com/110596345/215550138-6494a0f0-a2c3-490c-ace4-b996089e26d3.png)
4. Verify if the button UP takes (returns) you to the top of the page after one clicking
5. Verify if the button UP hides if the user returns to a place higher than 2nd screen (1600 px)
6. Verify if the button UP is located above the donate button according to the mockup
![Screenshot_14](https://user-images.githubusercontent.com/110596345/215456522-4b16309a-76b6-4796-b27b-6e6887ce3836.png)
7. Verify if the button UP remains after the modal window with donate was opened

**Expected result**
UP button allows the user to return to the top of the page in one click

**User story: https://github.com/ita-social-projects/StreetCode/issues/78**

**Comment by BDaria** [comment]
Adaptives added: desktop (1920px, 1600px, 1025px), tablet (768px), mobile (360px).
