### ISSUE TITLE
[Streetcode][Tablet] The page looks not according to mockup

### ISSUE THREAD

**Issue by iskoryk** [ita-social-projects/StreetCode#951]
**Environment:** Tablet 1024x768 and 768x1024
**Reproducible:** Always.
**Build found:** [8490f60](https://github.com/ita-social-projects/StreetCode/commit/8490f607507e781d172f910b7e6859e64e055861)

**Priority:** Low
**Severity:** Minor
**Type:** UI

**Preconditions:**
1. The Streetcode page is opened (e.g. ["Михайло Грушевський" page](https://stage.streetcode.com.ua/mykhailo-hrushevskyi)). 
2. [Mockup](https://www.figma.com/file/9ydz23Y1yKPGx92lsqBhak/StreetCode?type=design&node-id=5827-11457&mode=design&t=LHPP4j3ftWBaRs0r-0) is opened.

| # | **Steps to reproduce** | **Actual result** | **Expected result** | Status |
| --- | ---- | --- | ---- | ---- |
| 1 | 1. Scroll down to 'Wow-факти'.<br>2. Check the distance between the center 'Wow-факти' card and the navigation dots | 11 px.<br>The shadow of the card is clipped | 20 px.<br>The shadow of the card is fully displayed. [Mockup](https://www.figma.com/file/9ydz23Y1yKPGx92lsqBhak/StreetCode?type=design&node-id=4069-8003&mode=design&t=gHIWrP2MMUm7Ih1j-4) | Fail |
| 2 | Check the distance between _the left edge - left wow-факт card - wow-факт central card - right wow-факт card - the right edge_ | 2 - 17 - 17 - 4 (reproduce on tablet 768x1024) | 8 - 14 - 14 - 14 | Fail |
| 3 | 1. Scroll down to the 'Арт-галерея' field.<br>2. Check the distance between the pictures and navigation dots. | 33 px | 20 px [Mockup](https://www.figma.com/file/9ydz23Y1yKPGx92lsqBhak/StreetCode?type=design&node-id=4069-8490&mode=design&t=gD4UfcjUGWb8ZvUd-4) | Fail |
| 4 | Distance from the 'Перейти в Instagram' button to partners. | 54 px | 50 px [Mockup](https://www.figma.com/file/9ydz23Y1yKPGx92lsqBhak/StreetCode?type=design&node-id=4069-8490&mode=design&t=gHIWrP2MMUm7Ih1j-4) | Fail |
| 5 | Pay attention to the square from the header of fields. | The square from the header of each field extends too far from the left edge. | The square from the header of each field goes beyond the left edge for 18 px. | Fail |
| 6 | 1. Scroll to the Main StreetCode Block. <br>2. Check the position of the Audio button's bottom border and the Person card's bottom white border. | The Audio button's bottom border is 6px below the Person card's bottom white border. | The Audio button's bottom border is in line with the Person card's bottom white border. | Fail |  
| 7 | 1. Scroll to the Main StreetCode Block. <br>2. Pay attention to the left gray shadow of the person's image. | The left gray shadow of the person's image is not displayed. | The left gray shadow of the person's image is displayed. | Fail | 

**2.** <img width="385" alt="Screenshot 2023-12-13 at 16 50 08" src="https://github.com/ita-social-projects/StreetCode/assets/130586498/619c7e0c-b0c2-45c3-96ec-08c8987afc7e"> 

**5**. ![IMG_3463](https://github.com/ita-social-projects/StreetCode/assets/130586498/6217e9e6-b6ab-4e03-8e87-3804432388d8)

**6**. 
![баг нижня лінія 1](https://github.com/ita-social-projects/StreetCode/assets/160258291/01f18eaa-0b44-409f-9079-b8368c737274)

![баг нижня лінія 2](https://github.com/ita-social-projects/StreetCode/assets/160258291/d97fccb9-438a-4d7d-b840-52f6bd2c5482)

**7.**
![сіра тінь 1 мокап](https://github.com/ita-social-projects/StreetCode/assets/160258291/8072cdcb-2bd4-4c53-a499-4332f63b7c48)

![сіра тінь 2 стейдж](https://github.com/ita-social-projects/StreetCode/assets/160258291/b796cfc8-ed99-4382-80ff-dafe7f2f758d)

**User story :** #20, #26 
**Epic:** #19
**Test case:** #67, #614, #1269

**Comment by AlbinaVorobiova** [comment]
**New bugs are added to the table:**
Bug 6. The Audio button's bottom border is 6px below the Person card's bottom white border.
Bug 7. The left gray shadow of the person's image is not displayed.

Environment: Windows 11 (64 bit), Google Chrome Version 122.0.6261.112 (Official build), (64 bit), screen resolution 768x650px 
Build found:
