### ISSUE TITLE
[Test Case] [Donate button] Verify if the Donate button will allow the user to donate and support the project.

### ISSUE THREAD

**Issue by SvitlanaOleksiv** [ita-social-projects/StreetCode#96]
**Priority:  high**

**Description:**
Test case verifies if the Donate button will allow the user to donate and support the project

**Preconditions**
1. Go to “StreetCode” page

**Steps to reproduce**
1. Verify if the Donate button is displayed and pinned to the bottom right corner of the screen
2. Verify if the Donate button is displayed on a white background
![Screenshot_15](https://user-images.githubusercontent.com/110596345/215548940-d3daea29-5a6a-4004-85e6-6efa3c32a1d8.png)
4. Verify if  after hovering over the Donate button, a shadow appears behind the button
5. Verify if after clicking the Donate button a modal window with donate options opens ("+" near donate is absent)
![image](https://user-images.githubusercontent.com/110596345/215547215-5ecdf559-0722-42e6-9130-b93341ac434a.png)

6. Verify if the "X" button is displayed on the upper right corner of the modal window
7. Verify if the  clicking on "X" button closes a modal window
8. Verify if the user is reaching the bottom of a StreetCode - Donate Modal window appears automatically
9. Verify if the user earlier opened donate modal window via the button - modal window is not shown automatically
10. Verify if the user earlier viewed an automatically displayed window - it will not be displayed for a second time
11. Verify if the  user is able to type the amount of a donation on the modal window
12. Verify if  a button with the amount changes button color after clicking 
![image](https://user-images.githubusercontent.com/110596345/216162866-8cc24ecc-5469-48d6-bba9-c4a2571e6ac4.png)

**Expected result**
The donate button will allow the user to donate and support the project

**User story: https://github.com/ita-social-projects/StreetCode/issues/78**

**Comment by iskoryk** [comment]
Divide into two test cases #96 and #340.
1.1 Edit title - new [Test Case] [Donate button] Verify that the "Donate" button and modal window with donate options are visible and work #96
1.2 Update mockup.  4. Verify if after clicking the Donate button a modal window with donate options opens ("+" near donate is absent) - remove the text in brackets
1.3 Remove steps 10 and 11 (These steps will be performed in TC #340)
